const body = `
# Distance as meaning

A square in Kraków, a demonstration scattering the crowd, and a young singer stands still in the middle of it, because the tour bus pulling away carries a French tourist photographing everything, and the tourist has her face. Weronika holds her sheet music and watches herself leave. [The Double Life of Véronique](/film/the-double-life-of-veronique-1991) never explains what the two women are to each other: no séance, no separated-twins paperwork. The film commits to a single claim, and the claim is a measurement. These two lives, one Polish, one French, lie very close together. Everything downstream follows from taking that seriously.

## Criticism by proximity

Every catalogue ever printed keeps the two women apart. Nationality, language, profession, city: different on every line. What actually joins them is nothing a label can hold: the same face, the same flawed heart, the same unaccountable sense of not being alone in the world. So Kieślowski measures instead of filing. When Weronika collapses mid-concert and dies, Véronique, in Paris, gives up her own singing without being able to say why. No cause crosses the border; distance does. The film's wager is that the truest relations, between people and, I would argue, between films, are not category memberships but distances — how far one life sits from another in the space of what it is.

Our kinship layer is this wager turned into working furniture — readings placed in a common space, small distances trusted over loud labels ([kinship](/methodology/kinship), [embedding map](/methodology/embedding-map)). Kieślowski had the idea first and staged it better. The instrument rates his film V81, essential, to the four and a half stars in my log. Hand and ruler in the same pew, for once.

## The right face, the wrong man

[Asako I & II](/film/asako-i-ii-2018) runs the same geometry as cruelty. Asako's first love, Baku, walks out of her life without explanation. Two years later, in Tokyo, she meets Ryohei, who has Baku's face down to the last coordinate; Hamaguchi casts one actor as both men. Asako does what any resemblance engine does: accepts the nearest result as the thing she searched for. The film spends its whole length pricing the substitution. Ryohei matches Baku in the one dimension a glance can measure and diverges in every dimension that takes years to read: steady where Baku was weather, present where Baku was mostly a beautiful absence. When Baku resurfaces, famous now, Asako walks out of a settled life in one evening, gets partway up the coast, and turns around. Nearest-neighbour as romance, then as horror. Love begins as a resemblance query; the damage comes from forgetting the query was approximate. I gave it five stars. The instrument files it at V69, a deep cut, and I think my hand is right and the number defensible, in that order.

## What the puppet knows

Set side by side, these two films argue the point better than I can: what distance gives a critic, and what it flattens. No shelf holds them together: a Polish-French metaphysical drama and a Japanese romance share no genre, no decade, no market, and thinking in distances is the only reason I ever laid one against the other. The cost, both films state better than any sceptic. In Véronique, the puppeteer Alexandre carves two marionettes of her and explains that puppets get damaged in performance, so he needs two. Two objects identical to any measurement in the room, and the film's whole ache is that one is not the other. Asako needs two hours and a nearly wrecked life to reach the same point: a face is a lossy record of a person, and she fell in love with the record first.

The sceptics, who say criticism by proximity always reads slightly away from the film in front of it, can have their concession in full. The two films that taught me to take distance seriously both end by overruling it. Weronika's double rides out of the square unmet. Asako ends beside the man she chose over the perfect match, looking at a swollen river; he says it is filthy, she answers that it is still beautiful, and stays. Each film builds a resemblance-space, then stakes everything on a woman stepping out of it. The geometry that first paired these films for me has no coordinate for that step. Distance is the best beginning of a reading I know. Where readings end, the sceptics are right, and I have no rebuttal.
`;
export default body;
