const body = `
# When the canon scores low

The page that forced the decision was [Green Book](/film/green-book-2018). It won Best Picture; it sits on a canon list; and the honest reading came back at minus ten — below zero on a scale whose median across 6,701 scored films is about 36. So there it was, on one page: a film the [Academy](/lineage/oscar-best-picture) had crowned, wearing a [TakeScore](/methodology/takescore) that put it in the catalogue's basement. I had to decide what the [to.W letter](/methodology/why-a-film-is-in-the-index) above that number was allowed to say about it, and I spent longer on that one sentence than I would like to admit.

## The word I would not print

The easy move was to reach for the canon's own vocabulary. The film is on a list; call it **canon** and let the prestige do the work. But a letter that says "one of the essential films of its decade" sitting directly above a score of minus ten is not describing the film — it is describing a contradiction I decided not to resolve, and hoping the reader wouldn't look down. So I made the rule that the letter never borrows the word. When a canon-listed title scores low, it is described for what is plainly, verifiably true — **much-seen and much-talked-about** — and not one adjective more. That is what is accurate about [Forrest Gump](/film/forrest-gump-1994) (minus one) and [Titanic](/film/titanic-1997) (three) and [American Beauty](/film/american-beauty-1999) and [Braveheart](/film/braveheart-1995): everyone has seen them, everyone has an opinion, and few working critics would place them among the greatest films made. The standing is real. The letter simply declines to spend the canon's prestige on the film's behalf.

## Two numbers, allowed to disagree

The deeper choice was to let the two facts stand side by side without a referee. A film's place on a canon list and its TakeScore answer different questions. One records where a title landed in the culture and the archive; the other weighs what the film delivered against its cost and risk. I could have forced them into agreement — bent the score up to flatter the listing, or quietly hidden the listing when the score embarrassed it. I did neither. On the [Green Book](/film/green-book-2018) page the Best Picture badge and the minus-ten both remain, unreconciled, because **suppressing either one would be a lie about a fact I hold to be true.** The canon has its reasons; the scale has its rubric; and a reader who sees the gap is better informed than one handed a false peace.

## The confession in my own delight

I should name what this rule protects me from, because it is mostly me. There is a trope our own readings keep finding, [*The Award As Society's Absolution Ritual*](/trope/the-award-as-society-s-absolution-ritual) — the way a prize can be less a verdict on a film than a culture pardoning itself, comfortably, for two hours. I believe that reading about [Green Book](/film/green-book-2018). And that is exactly why I have to watch myself: a critic who *enjoys* catching the canon out, who feels a small clean pleasure when a beloved title posts a negative number, is running a mirror-image of the same ritual — absolving *himself*, this time, of the charge of being sentimental about cinema. The scale is not built to punish the crowd for loving [Titanic](/film/titanic-1997). If it were, I would trust it less. It is built to say, flatly, that wide love and canonical listing are two facts, and neither of them is the same as what the film gives back when you sit with it closely.

Which is the tidy version. Here is what I have not settled. A canon list is not static — it is revised, films rise and fall on it across decades, and a title that looks like a strange inclusion today may be recording a shift in taste I am simply too close to see. My scale judges the film on the screen now, on its own terms, and holds still while the canon moves. So when [Green Book](/film/green-book-2018) and its minus ten disagree, I have been assuming the number is the sober one and the list is the sentimental one. What if, on some of these rows, it is the other way around — and the list is early to something my rubric is built to miss?
`;
export default body;
