# -*- coding: utf-8 -*-
"""Build FilmCurio expansion candidate list (3 buckets, 3 waves), dedup vs existing 567."""
import csv, re, unicodedata, math
from collections import Counter

SEED = "/sessions/confident-intelligent-newton/mnt/filmcurio/data/seed/metatake_films_567.csv"

def norm(t):
    t = unicodedata.normalize("NFKD", t).encode("ascii","ignore").decode("ascii").lower()
    t = re.sub(r"\b(the|a|an)\b"," ",t)
    t = re.sub(r"[^a-z0-9]+"," ",t)
    return t.strip()

existing=set()
with open(SEED,encoding="utf-8") as f:
    for row in csv.DictReader(f):
        ti=(row.get("Film_Title") or "").strip()
        if ti: existing.add(norm(ti))

CANON=[
 ("2001: A Space Odyssey","Stanley Kubrick",1968,"USA/UK","S&S top-10 all-time; deepest sci-fi crit lit"),
 ("Citizen Kane","Orson Welles",1941,"USA","Canon cornerstone; deep-focus form, Bazin"),
 ("Vertigo","Alfred Hitchcock",1958,"USA","Mulvey gaze theory built on it; S&S #1 2012"),
 ("Tokyo Story","Yasujiro Ozu",1953,"Japan","S&S top-5; quietness/space crit lit"),
 ("Seven Samurai","Akira Kurosawa",1954,"Japan","Most-written-about action canon"),
 ("Psycho","Alfred Hitchcock",1960,"USA","Founding slasher; psychoanalytic crit"),
 ("The 400 Blows","Francois Truffaut",1959,"France","French New Wave anchor"),
 ("Breathless","Jean-Luc Godard",1960,"France","Jump-cut modernism; theory staple"),
 ("8 1/2","Federico Fellini",1963,"Italy","Self-reflexive cinema canon"),
 ("Bicycle Thieves","Vittorio De Sica",1948,"Italy","Italian neorealism keystone"),
 ("Persona","Ingmar Bergman",1966,"Sweden","Identity/doubling; heavily theorized"),
 ("The Seventh Seal","Ingmar Bergman",1957,"Sweden","Allegory/death iconography"),
 ("Apocalypse Now","Francis Ford Coppola",1979,"USA","War myth; high search + crit lit"),
 ("Taxi Driver","Martin Scorsese",1976,"USA","Scorsese already a hub; extends graph"),
 ("Chinatown","Roman Polanski",1974,"USA","Neo-noir canon, ideology readings"),
 ("A Clockwork Orange","Stanley Kubrick",1971,"UK","Violence/ideology; high search"),
 ("Dr. Strangelove","Stanley Kubrick",1964,"USA/UK","Cold-war satire canon"),
 ("Barry Lyndon","Stanley Kubrick",1975,"UK","Form/painterly image crit lit"),
 ("The Rules of the Game","Jean Renoir",1939,"France","S&S top-10; class allegory"),
 ("Andrei Rublev","Andrei Tarkovsky",1966,"USSR","Tarkovsky canon; art/faith"),
 ("Stalker","Andrei Tarkovsky",1979,"USSR","Zone allegory; huge crit lit"),
 ("Mirror","Andrei Tarkovsky",1975,"USSR","Memory/form canon"),
 ("Solaris","Andrei Tarkovsky",1972,"USSR","SF philosophy canon"),
 ("Rashomon","Akira Kurosawa",1950,"Japan","'Rashomon effect'; epistemology"),
 ("Ikiru","Akira Kurosawa",1952,"Japan","Existential canon"),
 ("La Dolce Vita","Federico Fellini",1960,"Italy","Modernity/spectacle"),
 ("L'Avventura","Michelangelo Antonioni",1960,"Italy","Antonioni alienation canon"),
 ("The Conformist","Bernardo Bertolucci",1970,"Italy","Fascism/psychoanalysis; form"),
 ("Au Hasard Balthazar","Robert Bresson",1966,"France","Bresson transcendental style"),
 ("Pickpocket","Robert Bresson",1959,"France","Bresson canon; grace/hands"),
 ("Pather Panchali","Satyajit Ray",1955,"India","Indian canon backbone (huge gap)"),
 ("The Battle of Algiers","Gillo Pontecorvo",1966,"Italy/Algeria","Anti-colonial; political-film canon"),
 ("M","Fritz Lang",1931,"Germany","Crowd/justice; early-sound crit lit"),
 ("Metropolis","Fritz Lang",1927,"Germany","SF/labor allegory; silent canon"),
 ("Nosferatu","F.W. Murnau",1922,"Germany","Vampire iconography origin"),
 ("Sunrise","F.W. Murnau",1927,"USA","Silent-form canon"),
 ("The Cabinet of Dr. Caligari","Robert Wiene",1920,"Germany","Expressionism origin"),
 ("Battleship Potemkin","Sergei Eisenstein",1925,"USSR","Montage theory source text"),
 ("The Passion of Joan of Arc","Carl Theodor Dreyer",1928,"France","Face/close-up canon"),
 ("City Lights","Charlie Chaplin",1931,"USA","Chaplin canon; sentiment/modernity"),
 ("Modern Times","Charlie Chaplin",1936,"USA","Machine/labor; high search"),
 ("Casablanca","Michael Curtiz",1942,"USA","Most-cited classic; high search"),
 ("Sunset Boulevard","Billy Wilder",1950,"USA","Hollywood-on-Hollywood canon"),
 ("Some Like It Hot","Billy Wilder",1959,"USA","Gender/comedy; Butler-adjacent"),
 ("Double Indemnity","Billy Wilder",1944,"USA","Film-noir template"),
 ("Singin' in the Rain","Stanley Donen",1952,"USA","Musical canon; high search"),
 ("The Searchers","John Ford",1956,"USA","Western/race ideology canon"),
 ("12 Angry Men","Sidney Lumet",1957,"USA","High search; group/justice"),
 ("Touch of Evil","Orson Welles",1958,"USA","Noir long-take canon"),
 ("North by Northwest","Alfred Hitchcock",1959,"USA","Hitchcock set-piece canon"),
 ("Rear Window","Alfred Hitchcock",1954,"USA","Voyeurism/gaze theory"),
 ("Lawrence of Arabia","David Lean",1962,"UK","Epic/Orientalism crit lit"),
 ("The Third Man","Carol Reed",1949,"UK","Noir/Vienna; canon"),
 ("Tokyo Drifter","Seijun Suzuki",1966,"Japan","Pop-art yakuza; form crit"),
 ("Woman in the Dunes","Hiroshi Teshigahara",1964,"Japan","Existential allegory canon"),
 ("Harakiri","Masaki Kobayashi",1962,"Japan","Bushido critique; canon"),
 ("Ugetsu","Kenji Mizoguchi",1953,"Japan","Mizoguchi ghost canon"),
 ("Sansho the Bailiff","Kenji Mizoguchi",1954,"Japan","Mizoguchi canon"),
 ("Late Spring","Yasujiro Ozu",1949,"Japan","Ozu marriage/space canon"),
 ("In the Realm of the Senses","Nagisa Oshima",1976,"Japan","Sexuality/transgression crit"),
 ("Aguirre, the Wrath of God","Werner Herzog",1972,"Germany","Herzog colonial madness canon"),
 ("Fitzcarraldo","Werner Herzog",1982,"Germany","Herzog obsession canon"),
 ("Ali: Fear Eats the Soul","Rainer Werner Fassbinder",1974,"Germany","Race/melodrama; Sirkian"),
 ("The Marriage of Maria Braun","Rainer Werner Fassbinder",1979,"Germany","Postwar allegory"),
 ("The Spirit of the Beehive","Victor Erice",1973,"Spain","Childhood/Francoism canon"),
 ("Cleo from 5 to 7","Agnes Varda",1962,"France","Varda time/gaze canon"),
 ("Jules and Jim","Francois Truffaut",1962,"France","New Wave love-triangle canon"),
 ("Contempt","Jean-Luc Godard",1963,"France","Cinema-on-cinema; gaze"),
 ("Pierrot le Fou","Jean-Luc Godard",1965,"France","Godard color/violence canon"),
 ("The Umbrellas of Cherbourg","Jacques Demy",1964,"France","Sung melodrama; canon"),
 ("Belle de Jour","Luis Bunuel",1967,"France","Fantasy/desire; psychoanalysis"),
 ("The Discreet Charm of the Bourgeoisie","Luis Bunuel",1972,"France","Surreal class satire"),
 ("Hiroshima Mon Amour","Alain Resnais",1959,"France","Memory/trauma; canon"),
 ("Last Year at Marienbad","Alain Resnais",1961,"France","Time/narration modernism"),
 ("Children of Paradise","Marcel Carne",1945,"France","Theatre/spectacle canon"),
 ("The Wages of Fear","Henri-Georges Clouzot",1953,"France","Suspense/labor canon"),
 ("Bonnie and Clyde","Arthur Penn",1967,"USA","New Hollywood violence turn"),
 ("The Graduate","Mike Nichols",1967,"USA","Generation/desire; high search"),
 ("The Wild Bunch","Sam Peckinpah",1969,"USA","Violence/Western elegy"),
 ("Nashville","Robert Altman",1975,"USA","Altman mosaic; Americana"),
 ("McCabe & Mrs. Miller","Robert Altman",1971,"USA","Revisionist Western canon"),
 ("The Conversation","Francis Ford Coppola",1974,"USA","Surveillance/sound; Chion"),
 ("Network","Sidney Lumet",1976,"USA","Media critique; high search"),
 ("Dog Day Afternoon","Sidney Lumet",1975,"USA","Queer/heist; ideology"),
 ("One Flew Over the Cuckoo's Nest","Milos Forman",1975,"USA","Foucault/institution readings"),
 ("A Woman Under the Influence","John Cassavetes",1974,"USA","Cassavetes performance canon"),
 ("Badlands","Terrence Malick",1973,"USA","Malick already a hub; extends graph"),
 ("Days of Heaven","Terrence Malick",1978,"USA","Malick image/nature canon"),
 ("Annie Hall","Woody Allen",1977,"USA","Romcom/form; high search"),
 ("Manhattan","Woody Allen",1979,"USA","City/romance canon"),
 ("Mean Streets","Martin Scorsese",1973,"USA","Early Scorsese; extends hub"),
 ("Don't Look Now","Nicolas Roeg",1973,"UK","Editing/grief; horror-adjacent canon"),
 ("Eraserhead","David Lynch",1977,"USA","Lynch already a hub; body/anxiety"),
 ("All About Eve","Joseph L. Mankiewicz",1950,"USA","Theatre/ambition; gender"),
 ("The Night of the Hunter","Charles Laughton",1955,"USA","Expressionist fable canon"),
 ("On the Waterfront","Elia Kazan",1954,"USA","Labor/conscience canon"),
 ("A Streetcar Named Desire","Elia Kazan",1951,"USA","Desire/gender; Method"),
 ("Viridiana","Luis Bunuel",1961,"Spain","Religion/transgression; Palme"),
 ("The Leopard","Luchino Visconti",1963,"Italy","Class/time; Visconti canon"),
 ("Rocco and His Brothers","Luchino Visconti",1960,"Italy","Migration/melodrama"),
 ("Salo, or the 120 Days of Sodom","Pier Paolo Pasolini",1975,"Italy","Power/fascism; extreme-cinema crit"),
 ("The Color of Pomegranates","Sergei Parajanov",1969,"USSR/Armenia","Tableau form; canon"),
 ("The Cranes Are Flying","Mikhail Kalatozov",1957,"USSR","Camera movement canon"),
 ("Ashes and Diamonds","Andrzej Wajda",1958,"Poland","Polish postwar canon"),
 ("Daisies","Vera Chytilova",1966,"Czechoslovakia","Feminist avant-garde canon"),
 ("Charulata","Satyajit Ray",1964,"India","Ray gaze/interior canon"),
 ("Stagecoach","John Ford",1939,"USA","Western/space; Ford canon"),
 ("Grand Illusion","Jean Renoir",1937,"France","War/class humanism canon"),
 ("It's a Wonderful Life","Frank Capra",1946,"USA","High search; Americana ideology"),
 ("Bringing Up Baby","Howard Hawks",1938,"USA","Screwball/gender canon"),
 ("Yojimbo","Akira Kurosawa",1961,"Japan","Genre-template canon"),
 ("Ran","Akira Kurosawa",1985,"Japan","Late Kurosawa Lear; color/war"),
]

CONTEMP=[
 ("One Battle After Another","Paul Thomas Anderson",2025,"USA","Oscar Best Picture 2026; PTA is a hub"),
 ("Sinners","Ryan Coogler",2025,"USA","Top-rated 2025; horror/Americana"),
 ("It Was Just an Accident","Jafar Panahi",2025,"Iran","Cannes 2025 Palme d'Or"),
 ("The Substance","Coralie Fargeat",2024,"France/UK","Body-horror/gaze; huge 2024 crit lit"),
 ("The Brutalist","Brady Corbet",2024,"USA","2024 awards; architecture/immigration"),
 ("Sentimental Value","Joachim Trier",2025,"Norway","Cannes 2025 Grand Prix; Trier is in"),
 ("Conclave","Edward Berger",2024,"UK/USA","2024 awards; institution/ritual"),
 ("Nickel Boys","RaMell Ross",2024,"USA","POV form; race; 2024 crit darling"),
 ("I'm Still Here","Walter Salles",2024,"Brazil","Oscar Intl Feature 2025; Salles is in"),
 ("All We Imagine as Light","Payal Kapadia",2024,"India","Cannes 2024 Grand Prix; Indian gap"),
 ("Decision to Leave","Park Chan-wook",2022,"South Korea","Park is a hub; gaze/noir"),
 ("Memoria","Apichatpong Weerasethakul",2021,"Thailand/Colombia","Apichatpong is in; sound/Chion"),
 ("Monster","Hirokazu Kore-eda",2023,"Japan","Kore-eda is a hub; perspective"),
 ("Evil Does Not Exist","Ryusuke Hamaguchi",2023,"Japan","Hamaguchi is a hub; nature/ethics"),
 ("The Boy and the Heron","Hayao Miyazaki",2023,"Japan","Miyazaki is a hub; late-style"),
 ("Flow","Gints Zilbalodis",2024,"Latvia","Oscar Animation 2025; dialogue-free"),
 ("The Holdovers","Alexander Payne",2023,"USA","Payne is in; class/melancholy"),
 ("May December","Todd Haynes",2023,"USA","Haynes is in; melodrama/gaze"),
 ("All of Us Strangers","Andrew Haigh",2023,"UK","Queer grief; ghost form"),
 ("Fallen Leaves","Aki Kaurismaki",2023,"Finland","Kaurismaki is in; deadpan"),
 ("Close","Lukas Dhont",2022,"Belgium","Boyhood/masculinity; Cannes"),
 ("Petite Maman","Celine Sciamma",2021,"France","Sciamma is in; childhood/time"),
 ("Saint Omer","Alice Diop",2022,"France","Trial/motherhood; Venice"),
 ("EO","Jerzy Skolimowski",2022,"Poland","Animal-POV; Bresson lineage"),
 ("Return to Seoul","Davy Chou",2022,"Cambodia/France","Adoption/identity; Korean gap"),
 ("First Cow","Kelly Reichardt",2019,"USA","Reichardt slow-cinema; friendship/capital"),
 ("Showing Up","Kelly Reichardt",2022,"USA","Art-labor; Reichardt"),
 ("Broker","Hirokazu Kore-eda",2022,"South Korea","Kore-eda + Korean cast; family"),
 ("Asteroid City","Wes Anderson",2023,"USA","Anderson is a hub; nested form"),
 ("The French Dispatch","Wes Anderson",2021,"USA","Anderson is a hub; anthology"),
 ("Moonrise Kingdom","Wes Anderson",2012,"USA","Anderson is a hub; childhood"),
 ("The Green Knight","David Lowery",2021,"USA","Myth/adaptation; A24"),
 ("Minari","Lee Isaac Chung",2020,"USA","Immigrant family; Korean-American"),
 ("The Farewell","Lulu Wang",2019,"USA/China","Diaspora/grief; high search"),
 ("Beau Is Afraid","Ari Aster",2023,"USA","Aster is a hub; anxiety/odyssey"),
 ("The Whale","Darren Aronofsky",2022,"USA","Aronofsky is a hub; body/shame"),
 ("Bardo","Alejandro Gonzalez Inarritu",2022,"Mexico","Inarritu is a hub; memory"),
 ("Maestro","Bradley Cooper",2023,"USA","Biopic/performance; Netflix"),
 ("El Conde","Pablo Larrain",2023,"Chile","Pinochet-as-vampire; allegory"),
 ("Okja","Bong Joon Ho",2017,"South Korea","Bong is a hub; capital/animal"),
 ("Mank","David Fincher",2020,"USA","Fincher is a hub; Hollywood/Welles"),
 ("I'm Thinking of Ending Things","Charlie Kaufman",2020,"USA","Kaufman; identity/dread"),
 ("The Trial of the Chicago 7","Aaron Sorkin",2020,"USA","Sorkin is in; politics/trial"),
 ("The Lost Daughter","Maggie Gyllenhaal",2021,"USA/Greece","Motherhood/ambivalence"),
 ("Civil War","Alex Garland",2024,"USA","Garland is in; image/witness"),
 ("Challengers","Luca Guadagnino",2024,"USA","Guadagnino is in; desire/sport"),
 ("The Iron Claw","Sean Durkin",2023,"USA","Masculinity/body; wrestling"),
 ("Frankenstein","Guillermo del Toro",2025,"USA/Mexico","del Toro is in; myth/body; Oscar nom 2026"),
 ("Hamnet","Chloe Zhao",2025,"UK/USA","Zhao is in; grief; Oscar nom 2026"),
 ("Bugonia","Yorgos Lanthimos",2025,"USA","Lanthimos is a hub; Oscar nom 2026"),
 ("Marty Supreme","Josh Safdie",2025,"USA","Safdie energy; Oscar nom 2026"),
 ("Train Dreams","Clint Bentley",2025,"USA","Americana/labor; Oscar nom 2026"),
 ("The Secret Agent","Kleber Mendonca Filho",2025,"Brazil","Cannes 2025 Director+Actor"),
 ("Father Mother Sister Brother","Jim Jarmusch",2025,"USA","Venice 2025 Golden Lion"),
 ("The Voice of Hind Rajab","Kaouther Ben Hania",2025,"Tunisia","Venice 2025 Grand Jury; Gaza"),
 ("The Smashing Machine","Benny Safdie",2025,"USA","Venice 2025 Best Director"),
 ("Sirat","Oliver Laxe",2025,"Spain","Cannes 2025 Jury Prize"),
 ("Sound of Falling","Mascha Schilinski",2025,"Germany","Cannes 2025 Jury Prize"),
 ("Dreams","Dag Johan Haugerud",2025,"Norway","Berlinale 2025 Golden Bear"),
 ("Blue Moon","Richard Linklater",2025,"USA","Linklater is a hub; Berlinale 2025"),
 ("The Mastermind","Kelly Reichardt",2025,"USA","Reichardt; 2025 crit pick"),
 ("Hard Truths","Mike Leigh",2024,"UK","Leigh realism; performance"),
 ("A Real Pain","Jesse Eisenberg",2024,"USA/Poland","Memory/trauma tourism; 2024"),
 ("A Complete Unknown","James Mangold",2024,"USA","Mangold is in; biopic/myth"),
 ("Sing Sing","Greg Kwedar",2024,"USA","Prison/theatre; performance"),
 ("Emilia Perez","Jacques Audiard",2024,"France","Audiard is a hub; trans/genre"),
 ("The Girl with the Needle","Magnus von Horn",2024,"Denmark","B&W horror-history; Oscar nom"),
 ("Bird","Andrea Arnold",2024,"UK","Arnold is a hub; social-realist/magic"),
 ("Corsage","Marie Kreutzer",2022,"Austria","Empress/biopic revisionism"),
 ("Godland","Hlynur Palmason",2022,"Iceland/Denmark","Colonial/landscape; form"),
 ("The Quiet Girl","Colm Bairead",2022,"Ireland","Childhood/care; Irish-language"),
 ("The Innocents","Eskil Vogt",2021,"Norway","Childhood/power; horror-adjacent"),
 ("Beanpole","Kantemir Balagov",2019,"Russia","Postwar trauma; color/body"),
 ("Pacifiction","Albert Serra",2022,"France","Colonial dread; slow cinema"),
 ("About Dry Grasses","Nuri Bilge Ceylan",2023,"Turkey","Ceylan is a hub; talk/ethics"),
 ("Plan 75","Chie Hayakawa",2022,"Japan","Aging/biopolitics; Foucault"),
 ("Sick of Myself","Kristoffer Borgli",2022,"Norway","Attention/narcissism satire"),
 ("The Souvenir","Joanna Hogg",2019,"UK","Memory/autofiction; class"),
 ("The Taste of Things","Tran Anh Hung",2023,"France","Food/labor/desire; Cannes Director"),
 ("The Eight Mountains","Felix van Groeningen",2022,"Italy","Friendship/landscape"),
 ("Great Freedom","Sebastian Meise",2021,"Austria","Para.175/queer history; Foucault"),
]

POPULAR=[
 ("Star Wars","George Lucas",1977,"USA","Franchise origin (only sequels in); myth"),
 ("Alien","Ridley Scott",1979,"USA","Creed 'monstrous-feminine' source text"),
 ("Jaws","Steven Spielberg",1975,"USA","Blockbuster origin; Jameson/ideology"),
 ("The Exorcist","William Friedkin",1973,"USA","Horror canon; body/religion crit"),
 ("Rosemary's Baby","Roman Polanski",1968,"USA","Pregnancy-horror; feminist crit"),
 ("The Texas Chain Saw Massacre","Tobe Hooper",1974,"USA","Slasher theory source"),
 ("Suspiria","Dario Argento",1977,"Italy","Color/giallo; horror crit lit"),
 ("The Lord of the Rings: The Return of the King","Peter Jackson",2003,"NZ/USA","Trilogy gap; myth; huge search"),
 ("The Lord of the Rings: The Two Towers","Peter Jackson",2002,"NZ/USA","Trilogy gap; myth"),
 ("Dune","Denis Villeneuve",2021,"USA","Villeneuve is a hub; only Lynch Dune in"),
 ("Dune: Part Two","Denis Villeneuve",2024,"USA","Villeneuve hub; ecology/power"),
 ("Spider-Man: Across the Spider-Verse","Joaquim Dos Santos",2023,"USA","Spider-Verse gap; form/animation"),
 ("The Batman","Matt Reeves",2022,"USA","Noir superhero; high search"),
 ("Avengers: Infinity War","Anthony Russo",2018,"USA","MCU hub; only Avengers/Endgame in"),
 ("Spider-Man 2","Sam Raimi",2004,"USA","Raimi is in; superhero ethics"),
 ("Superman","Richard Donner",1978,"USA","Superhero myth origin; high search"),
 ("Mad Max 2: The Road Warrior","George Miller",1981,"Australia","Miller is a hub; wasteland myth"),
 ("Indiana Jones and the Temple of Doom","Steven Spielberg",1984,"USA","Spielberg hub; colonial crit"),
 ("Rocky","John G. Avildsen",1976,"USA","Only Rocky IV in; masculinity/Reagan"),
 ("Close Encounters of the Third Kind","Steven Spielberg",1977,"USA","Spielberg hub; wonder/sublime"),
 ("Planet of the Apes","Franklin J. Schaffner",1968,"USA","Allegory/race; SF canon"),
 ("Night of the Living Dead","George A. Romero",1968,"USA","Zombie/race allegory source"),
 ("Dawn of the Dead","George A. Romero",1978,"USA","Consumerism/zombie; Jameson"),
 ("Audition","Takashi Miike",1999,"Japan","J-horror; gender/body crit"),
 ("Ringu","Hideo Nakata",1998,"Japan","J-horror origin (US Ring is in)"),
 ("A Tale of Two Sisters","Kim Jee-woon",2003,"South Korea","K-horror; family/psyche"),
 ("I Saw the Devil","Kim Jee-woon",2010,"South Korea","Revenge/violence; K-cinema hub"),
 ("The Host","Bong Joon Ho",2006,"South Korea","Bong is a hub; monster/politics"),
 ("Thirst","Park Chan-wook",2009,"South Korea","Park is a hub; vampire/desire"),
 ("Cure","Kiyoshi Kurosawa",1997,"Japan","Hypnosis/dread; crit darling"),
 ("Possession","Andrzej Zulawski",1981,"France/Germany","Body/marriage horror; cult crit"),
 ("The Wicker Man","Robin Hardy",1973,"UK","Folk-horror canon source"),
 ("The Evil Dead","Sam Raimi",1981,"USA","Raimi is in; cabin/horror form"),
 ("Talk to Me","Danny Philippou",2022,"Australia","New horror; grief/possession"),
 ("Longlegs","Osgood Perkins",2024,"USA","2024 horror hit; dread/form"),
 ("X","Ti West",2022,"USA","Meta-slasher; body/aging"),
 ("Pearl","Ti West",2022,"USA","Technicolor horror; star/gaze"),
 ("I Saw the TV Glow","Jane Schoenbrun",2024,"USA","Trans allegory; media/horror"),
 ("Howl's Moving Castle","Hayao Miyazaki",2004,"Japan","Ghibli gap; Miyazaki hub"),
 ("Kiki's Delivery Service","Hayao Miyazaki",1989,"Japan","Ghibli gap; coming-of-age"),
 ("Castle in the Sky","Hayao Miyazaki",1986,"Japan","Ghibli gap; tech/nature"),
 ("Porco Rosso","Hayao Miyazaki",1992,"Japan","Ghibli gap; fascism/flight"),
 ("The Wind Rises","Hayao Miyazaki",2013,"Japan","Ghibli gap; war/creation ethics"),
 ("The Tale of the Princess Kaguya","Isao Takahata",2013,"Japan","Takahata is in; form/myth"),
 ("Only Yesterday","Isao Takahata",1991,"Japan","Takahata; memory/rural"),
 ("Ponyo","Hayao Miyazaki",2008,"Japan","Ghibli gap; childhood/sea"),
 ("Paprika","Satoshi Kon",2006,"Japan","Kon is in; dream/media"),
 ("Tokyo Godfathers","Satoshi Kon",2003,"Japan","Kon is in; city/family"),
 ("Millennium Actress","Satoshi Kon",2001,"Japan","Kon is in; memory/cinema"),
 ("Toy Story 3","Lee Unkrich",2010,"USA","Pixar hub; mortality/objects"),
 ("Monsters, Inc.","Pete Docter",2001,"USA","Docter is in; fear/labor"),
 ("Soul","Pete Docter",2020,"USA","Docter is in; existential"),
 ("The Iron Giant","Brad Bird",1999,"USA","Bird is in; pacifism/Cold War"),
 ("Toy Story 2","John Lasseter",1999,"USA","Pixar hub; collecting/identity"),
 ("Pinocchio","Ben Sharpsteen",1940,"USA","Disney canon; fairy-tale/ideology"),
 ("Fantasia","James Algar",1940,"USA","Music/abstraction; canon"),
 ("Snow White and the Seven Dwarfs","David Hand",1937,"USA","Feature-animation origin; gender"),
 ("Aladdin","Ron Clements",1992,"USA","Orientalism crit lit; high search"),
 ("Mulan","Tony Bancroft",1998,"USA","Gender/nation; high search"),
 ("Moana","Ron Clements",2016,"USA","Myth/Pacific; representation"),
 ("Zootopia","Byron Howard",2016,"USA","Allegory/race/policing"),
 ("Encanto","Jared Bush",2021,"USA","Family/trauma; huge search"),
 ("The Triplets of Belleville","Sylvain Chomet",2003,"France","Form/satire; animation crit"),
 ("Wolfwalkers","Tomm Moore",2020,"Ireland","Cartoon Saloon; colonial/nature"),
 ("Flee","Jonas Poher Rasmussen",2021,"Denmark","Animated doc; refugee/memory"),
 ("Fantastic Planet","Rene Laloux",1973,"France","SF allegory; animation canon"),
 ("Watership Down","Martin Rosen",1978,"UK","Myth/violence; animation"),
 ("The Act of Killing","Joshua Oppenheimer",2012,"Denmark","Doc; perpetrator/performance"),
 ("Sans Soleil","Chris Marker",1983,"France","Essay-film canon; memory/image"),
 ("Shoah","Claude Lanzmann",1985,"France","Holocaust doc; testimony"),
 ("Night and Fog","Alain Resnais",1956,"France","Holocaust essay-film canon"),
 ("Grizzly Man","Werner Herzog",2005,"USA","Herzog doc; nature/madness"),
 ("Hoop Dreams","Steve James",1994,"USA","Doc; race/class/sport"),
 ("The Thin Blue Line","Errol Morris",1988,"USA","Doc; truth/reenactment"),
 ("F for Fake","Orson Welles",1973,"France/Iran","Essay-film; authorship/fakery"),
 ("O.J.: Made in America","Ezra Edelman",2016,"USA","Doc; race/celebrity/media"),
 ("Stories We Tell","Sarah Polley",2012,"Canada","Doc; memory/family/truth"),
 ("Free Solo","Elizabeth Chai Vasarhelyi",2018,"USA","Doc; risk/body; high search"),
 ("Monty Python and the Holy Grail","Terry Gilliam",1975,"UK","Gilliam is in; parody/form"),
 ("Life of Brian","Terry Jones",1979,"UK","Satire/religion; high search"),
 ("Shaun of the Dead","Edgar Wright",2004,"UK","Wright is a hub; genre-parody"),
 ("Borat","Larry Charles",2006,"USA","Satire/performance; ideology"),
 ("The Blues Brothers","John Landis",1980,"USA","Landis is in; music/Americana"),
]

# ---- additional CANON (deepen auteurs in catalog + fill African/Taiwanese/HK New Wave gaps)
CANON += [
 ("The Good, the Bad and the Ugly","Sergio Leone",1966,"Italy","Leone (OUaTime in America in); Western myth"),
 ("Once Upon a Time in the West","Sergio Leone",1968,"Italy","Leone; Western elegy canon"),
 ("Le Samourai","Jean-Pierre Melville",1967,"France","Minimalist noir; huge influence"),
 ("Army of Shadows","Jean-Pierre Melville",1969,"France","Resistance/ethics; canon"),
 ("Le Cercle Rouge","Jean-Pierre Melville",1970,"France","Heist/fatalism"),
 ("Playtime","Jacques Tati",1967,"France","Modernity/architecture; form canon"),
 ("Mon Oncle","Jacques Tati",1958,"France","Modernity satire"),
 ("The Red Shoes","Michael Powell",1948,"UK","Art/obsession; Technicolor canon"),
 ("A Matter of Life and Death","Michael Powell",1946,"UK","Powell-Pressburger; afterlife/color"),
 ("Black Narcissus","Michael Powell",1947,"UK","Repression/color; canon"),
 ("Paths of Glory","Stanley Kubrick",1957,"USA","Kubrick; war/class injustice"),
 ("Lolita","Stanley Kubrick",1962,"USA/UK","Kubrick; desire/satire"),
 ("Ordet","Carl Theodor Dreyer",1955,"Denmark","Faith/miracle; Dreyer canon"),
 ("Wild Strawberries","Ingmar Bergman",1957,"Sweden","Memory/aging; Bergman"),
 ("Cries and Whispers","Ingmar Bergman",1972,"Sweden","Death/red; Bergman"),
 ("Fanny and Alexander","Ingmar Bergman",1982,"Sweden","Childhood/theatre; Bergman"),
 ("Scenes from a Marriage","Ingmar Bergman",1973,"Sweden","Marriage; talk-cinema"),
 ("The Earrings of Madame de...","Max Ophuls",1953,"France","Camera movement/objects canon"),
 ("L'Atalante","Jean Vigo",1934,"France","Poetic realism canon"),
 ("Throne of Blood","Akira Kurosawa",1957,"Japan","Macbeth/Noh; Kurosawa"),
 ("High and Low","Akira Kurosawa",1963,"Japan","Class/crime; form"),
 ("The Hidden Fortress","Akira Kurosawa",1958,"Japan","Star Wars source; adventure"),
 ("Floating Weeds","Yasujiro Ozu",1959,"Japan","Ozu color; theatre/family"),
 ("An Autumn Afternoon","Yasujiro Ozu",1962,"Japan","Ozu final; marriage/time"),
 ("The Life of Oharu","Kenji Mizoguchi",1952,"Japan","Woman's suffering; Mizoguchi"),
 ("Kwaidan","Masaki Kobayashi",1964,"Japan","Ghost-story form; color"),
 ("Onibaba","Kaneto Shindo",1964,"Japan","Folk-horror/sexuality"),
 ("Yi Yi","Edward Yang",2000,"Taiwan","Taiwanese New Wave (major gap)"),
 ("A Brighter Summer Day","Edward Yang",1991,"Taiwan","Youth/history epic; canon"),
 ("Days of Being Wild","Wong Kar-wai",1990,"Hong Kong","WKW hub; time/longing"),
 ("Happy Together","Wong Kar-wai",1997,"Hong Kong","WKW; queer/diaspora"),
 ("Fallen Angels","Wong Kar-wai",1995,"Hong Kong","WKW; night-city form"),
 ("2046","Wong Kar-wai",2004,"Hong Kong","WKW; memory/SF"),
 ("The Assassin","Hou Hsiao-hsien",2015,"Taiwan","Hou (City of Sadness in); wuxia/form"),
 ("Flowers of Shanghai","Hou Hsiao-hsien",1998,"Taiwan","Hou; interior/ritual"),
 ("To Live","Zhang Yimou",1994,"China","Zhang (Red Lantern in); history/survival"),
 ("Ju Dou","Zhang Yimou",1990,"China","Zhang; color/transgression"),
 ("Platform","Jia Zhangke",2000,"China","Jia (3 in); reform-era epic"),
 ("Aparajito","Satyajit Ray",1956,"India","Apu trilogy; Ray"),
 ("The World of Apu","Satyajit Ray",1959,"India","Apu trilogy; Ray"),
 ("The Music Room","Satyajit Ray",1958,"India","Ray; decline/music"),
 ("Touki Bouki","Djibril Diop Mambety",1973,"Senegal","African canon (major gap); Diop lineage"),
 ("Black Girl","Ousmane Sembene",1966,"Senegal","Postcolonial canon; Sembene"),
 ("Xala","Ousmane Sembene",1975,"Senegal","Postcolonial satire"),
 ("Yeelen","Souleymane Cisse",1987,"Mali","African myth canon"),
 ("Memories of Underdevelopment","Tomas Gutierrez Alea",1968,"Cuba","Revolution/intellectual; canon"),
 ("Black God, White Devil","Glauber Rocha",1964,"Brazil","Cinema Novo canon"),
 ("The Official Story","Luis Puenzo",1985,"Argentina","Dictatorship/memory; Oscar"),
 ("Pixote","Hector Babenco",1981,"Brazil","Street children; realism"),
 ("Sweet Smell of Success","Alexander Mackendrick",1957,"USA","Media/power; noir canon"),
 ("Out of the Past","Jacques Tourneur",1947,"USA","Noir template"),
 ("The Lady from Shanghai","Orson Welles",1947,"USA","Welles; mirror/noir"),
]

# ---- additional CONTEMPORARY (auteur-deepening + recent festival/streaming)
CONTEMP += [
 ("Pain and Glory","Pedro Almodovar",2019,"Spain","Almodovar big hub; memory/autofiction"),
 ("Parallel Mothers","Pedro Almodovar",2021,"Spain","Almodovar; motherhood/history"),
 ("All About My Mother","Pedro Almodovar",1999,"Spain","Almodovar; performance/identity"),
 ("Volver","Pedro Almodovar",2006,"Spain","Almodovar; ghosts/women"),
 ("The Room Next Door","Pedro Almodovar",2024,"Spain/USA","Venice 2024 Golden Lion; Almodovar"),
 ("Still Walking","Hirokazu Kore-eda",2008,"Japan","Kore-eda hub; family/loss"),
 ("Nobody Knows","Hirokazu Kore-eda",2004,"Japan","Kore-eda; abandonment"),
 ("Like Father, Like Son","Hirokazu Kore-eda",2013,"Japan","Kore-eda; nature/nurture"),
 ("Our Little Sister","Hirokazu Kore-eda",2015,"Japan","Kore-eda; sisters/seasons"),
 ("A Hidden Life","Terrence Malick",2019,"USA","Malick hub; conscience/faith"),
 ("The Father","Florian Zeller",2020,"UK","Dementia/form; performance"),
 ("Sound of Metal","Darius Marder",2019,"USA","Deafness/sound; Chion-adjacent"),
 ("Women Talking","Sarah Polley",2022,"USA","Faith/feminism; talk-cinema"),
 ("Pieces of a Woman","Kornel Mundruczo",2020,"USA","Grief/long-take birth"),
 ("His House","Remi Weekes",2020,"UK","Refugee horror; allegory"),
 ("The Wonder","Sebastian Lelio",2022,"Ireland/UK","Lelio (Gloria in); faith/body"),
 ("Athena","Romain Gavras",2022,"France","Banlieue/long-take; politics"),
 ("Quo Vadis, Aida?","Jasmila Zbanic",2020,"Bosnia","Srebrenica; witness"),
 ("Holy Spider","Ali Abbasi",2022,"Iran/Denmark","Abbasi (Border in); gender/violence"),
 ("The Apprentice","Ali Abbasi",2024,"USA","Abbasi; power/myth"),
 ("No Bears","Jafar Panahi",2022,"Iran","Panahi; image/border"),
 ("Four Daughters","Kaouther Ben Hania",2023,"Tunisia","Doc-hybrid; performance/memory"),
 ("Dahomey","Mati Diop",2024,"France/Senegal","Berlinale 2024 Golden Bear; Diop (Atlantics in)"),
 ("The Blue Caftan","Maryam Touzani",2022,"Morocco","Queer/craft; Maghreb"),
 ("An Elephant Sitting Still","Hu Bo",2018,"China","Despair epic; slow cinema"),
 ("Long Day's Journey Into Night","Bi Gan",2018,"China","Bi Gan (Cannes 2025); 3D long-take dream"),
 ("So Long, My Son","Wang Xiaoshuai",2019,"China","One-child policy; epic melodrama"),
 ("The Wild Goose Lake","Diao Yinan",2019,"China","Neo-noir; neon/crime"),
 ("A Sun","Chung Mong-hong",2019,"Taiwan","Family/guilt; Taiwanese"),
 ("Columbus","Kogonada",2017,"USA","Architecture/grief; form"),
 ("After Yang","Kogonada",2021,"USA","AI/memory/family; Kogonada"),
 ("20th Century Women","Mike Mills",2016,"USA","Mills; feminism/era"),
 ("C'mon C'mon","Mike Mills",2021,"USA","Mills; care/listening"),
 ("Vortex","Gaspar Noe",2021,"France","Split-screen; aging/death"),
 ("Climax","Gaspar Noe",2018,"France","Body/dance/dread"),
 ("Enter the Void","Gaspar Noe",2009,"France","POV/afterlife; form"),
 ("Robot Dreams","Pablo Berger",2023,"Spain","Animation; friendship/loss; no dialogue"),
 ("Memoir of a Snail","Adam Elliot",2024,"Australia","Claymation; melancholy"),
 ("A Different Man","Aaron Schimberg",2024,"USA","Face/identity; A24"),
 ("Janet Planet","Annie Baker",2023,"USA","Childhood/time; playwright-film"),
 ("Do Not Expect Too Much from the End of the World","Radu Jude",2023,"Romania","Labor/media satire; form"),
 ("Passages","Ira Sachs",2023,"France","Desire/triangle; Sachs"),
 ("Totem","Lila Aviles",2023,"Mexico","Child-POV; family/death"),
 ("The Teachers' Lounge","Ilker Catak",2023,"Germany","Institution/paranoia; Oscar nom"),
 ("Society of the Snow","J.A. Bayona",2023,"Spain","Survival/ethics; Oscar nom"),
 ("How to Have Sex","Molly Manning Walker",2023,"UK","Consent/youth; Cannes UCR"),
 ("The Settlers","Felipe Galvez",2023,"Chile","Colonial violence; Western"),
 ("Living","Oliver Hermanus",2022,"UK","Ikiru remake; mortality/bureaucracy"),
 ("Nope","Jordan Peele",2022,"USA","Peele hub (Get Out/Us in); spectacle/gaze"),
 ("All Dirt Roads Taste of Salt","Raven Jackson",2023,"USA","Memory/Black-Southern; form"),
 ("Cairo Conspiracy","Tarik Saleh",2022,"Sweden/Egypt","Institution/faith thriller"),
]

# ---- additional POPULAR/GENRE (HK action, anime, cult, docs, high-search animation)
POPULAR += [
 ("Hero","Zhang Yimou",2002,"China","Wuxia spectacle; ideology debate; high search"),
 ("House of Flying Daggers","Zhang Yimou",2004,"China","Wuxia; color/romance"),
 ("Hard Boiled","John Woo",1992,"Hong Kong","Woo (Face/Off in); gun-fu canon"),
 ("The Killer","John Woo",1989,"Hong Kong","Woo; heroic-bloodshed canon"),
 ("Enter the Dragon","Robert Clouse",1973,"Hong Kong/USA","Bruce Lee; martial-arts icon; high search"),
 ("Ip Man","Wilson Yip",2008,"Hong Kong","Martial-arts franchise; nationalism"),
 ("Police Story","Jackie Chan",1985,"Hong Kong","Chan stunt-canon; high search"),
 ("Stand by Me","Rob Reiner",1986,"USA","Reiner (5 in); coming-of-age; high search"),
 ("Labyrinth","Jim Henson",1986,"UK/USA","Cult fantasy; high search"),
 ("The NeverEnding Story","Wolfgang Petersen",1984,"Germany","Fantasy; childhood/story"),
 ("Willy Wonka & the Chocolate Factory","Mel Stuart",1971,"USA","Cult; morality fable; high search"),
 ("Young Frankenstein","Mel Brooks",1974,"USA","Parody canon; Brooks"),
 ("Blazing Saddles","Mel Brooks",1974,"USA","Satire/race; Brooks"),
 ("Time Bandits","Terry Gilliam",1981,"UK","Gilliam hub; history/fantasy"),
 ("A Silent Voice","Naoko Yamada",2016,"Japan","Anime; disability/bullying; high search"),
 ("Weathering with You","Makoto Shinkai",2019,"Japan","Shinkai (Your Name in); climate/teen"),
 ("Suzume","Makoto Shinkai",2022,"Japan","Shinkai; disaster/grief"),
 ("Wolf Children","Mamoru Hosoda",2012,"Japan","Hosoda; motherhood/folklore"),
 ("Belle","Mamoru Hosoda",2021,"Japan","Hosoda; virtual/identity"),
 ("The Wild Robot","Chris Sanders",2024,"USA","Animation; nature/care; 2024 hit"),
 ("Inside Out 2","Kelsey Mann",2024,"USA","Pixar; emotion/adolescence; huge box office"),
 ("Man on Wire","James Marsh",2008,"UK","Doc; high search; risk/art"),
 ("Searching for Sugar Man","Malik Bendjelloul",2012,"Sweden/UK","Doc; myth/music"),
 ("Senna","Asif Kapadia",2010,"UK","Doc; sport/icon"),
 ("Citizenfour","Laura Poitras",2014,"USA","Doc; surveillance/Snowden"),
 ("Summer of Soul","Questlove",2021,"USA","Doc; music/erasure/archive"),
]

# Legitimately-distinct same-title films (remakes/coincidence) to keep despite norm collision
KEEP={("dune",2021),("batman",2022),("killer",1989),("hero",2002)}

def to_waves(rows,bucket):
    kept=[r for r in rows if norm(r[0]) not in existing or (norm(r[0]),r[2]) in KEEP]
    dropped=[r[0] for r in rows if norm(r[0]) in existing and (norm(r[0]),r[2]) not in KEEP]
    n=len(kept); w1=math.ceil(n/3); w2=math.ceil((n-w1)/2)
    out=[]
    for i,r in enumerate(kept):
        w=1 if i<w1 else (2 if i<w1+w2 else 3)
        out.append((w,bucket)+r)
    return out,dropped,n

allrows=[]; report={}
for rows,bucket in [(CANON,"Canon backfill"),(CONTEMP,"Contemporary curation"),(POPULAR,"Popular/genre depth")]:
    w,dropped,n=to_waves(rows,bucket); allrows+=w; report[bucket]=(n,dropped)

OUT="/sessions/confident-intelligent-newton/mnt/outputs/filmcurio_candidates.csv"
with open(OUT,"w",newline="",encoding="utf-8") as f:
    wcsv=csv.writer(f)
    wcsv.writerow(["Wave","Bucket","Film_Title","Film_Director_Name","Year","Country","Why_curated"])
    for row in sorted(allrows,key=lambda x:(x[0],x[1])):
        wcsv.writerow(list(row))

# internal dup check (same normalized title appearing twice across candidate list)
seen=Counter((norm(r[2]),r[4]) for r in allrows)  # (norm title, year)
internal_dups=[k for k,c in seen.items() if c>1]
title_only=Counter(norm(r[2]) for r in allrows)
same_title_diff_year=[t for t,c in title_only.items() if c>1]
print("INTERNAL exact dups (title+year):", internal_dups)
print("Same-title different-year (intended remakes/distinct):", same_title_diff_year)
print("TOTAL candidates:",len(allrows))
bc=Counter(r[1] for r in allrows); wc=Counter(r[0] for r in allrows)
tot=len(allrows)
print("By bucket:",{k:(v,f"{100*v/tot:.0f}%") for k,v in bc.items()})
print("By wave:",dict(sorted(wc.items())))
for b,(n,dropped) in report.items():
    print(f"  {b}: kept {n}; dropped-as-dup {len(dropped)} -> {dropped}")
print("CSV ->",OUT)
