/** My Room v3 — the English string table (spec §5, complete).
 *  Every user-facing string in /room routes through this module so a future
 *  i18n pass is a file swap. Tone: terminal-terse + honest. Honesty lines are
 *  promises — do not soften them. Mono data labels (NAV, WWI, V/C/R/U, tier
 *  names) are product vocabulary, not prose: they never get translated. */

export const STR = {
  shell: {
    railAria: "Room navigation",
    railFooter: "Your cinematic asset operating system · Metatake",
    railImport: "Import",
    refresh: "Refresh",
    close: "Close (ESC)",
    back: "Back",
    brief: "Brief",
    briefTitle: "Page brief",
    inspectorTitle: "Details · Why",
    inspectorEmpty: "Click any item — details and the why open here.",
    publicProfile: "Public profile",
    navChipTitle: "NAV — click for the performance summary",
    navSummaryTitle: "Performance — summary",
    openPerformance: "Open Performance →",
  },
  cmdk: {
    placeholder: "Search films & pages",
    films: "FILMS",
    pages: "PAGES",
    recent: "RECENT",
    film: "Film",
    page: "Page",
    empty: "No results",
  },
  quickRate: {
    placeholder: "Search the film you just watched — one star-tap logs it.",
    searching: "Searching…",
    empty: "No results",
  },
  toast: {
    kept: (title: string) => `"${title}" added to your slate`,
    seen: (title: string) => `"${title}" logged as seen`,
    dismissed: (title: string) => `"${title}" won't be recommended again`,
    rated: (title: string, n: number) => `"${title}" ★${n} — logged as seen`,
    released: (title: string) => `"${title}" released from your slate`,
    restored: (title: string) => `"${title}" restored — back in the pool`,
    undo: "Undo",
    saveFail: (msg: string) => `Couldn't save — ${msg}`,
    logFail: (msg: string) => `Couldn't log — ${msg}`,
    rateFail: (msg: string) => `Couldn't rate — ${msg}`,
  },
  row: {
    keep: "Keep",
    kept: "Kept",
    seen: "Seen",
    dismiss: "Not interested",
    streaming: "Streaming now",
    risk: (n: number) => `Risk ${n}`,
    fit: "Fit",
    expand: "Score anatomy",
  },
  insp: {
    why: "Why this film",
    whyEmpty: "No reason data for this candidate yet — check the fundamentals below.",
    actNow: "Act now",
    myRating: "My rating",
    ratingHint: "0.5–5 · rating implies seen",
  },
  cc: {
    fundamentals: "Fundamentals",
    unscored: "Not scored by Cinecodex yet · awaiting analysis",
    uNetValue: "U Net value",
    confidence: "Confidence",
    confidenceTitle: "Measured confidence",
    risk: (n: number) => `Risk ${n}`,
    ours: "Ours",
    external: "External",
    canon: "Canon",
    standing: "Standing",
    discovery: "Discovery",
    market: "Market",
    analysis: "Analysis",
    neverBlend: "Ours, external and canon stay separate — never blended into one number.",
    fullCard: "Full appraisal · 13 sub-scores →",
  },
  /** "{feature} unlocks at {need} {unit} — you have {have}." */
  forming: {
    line: (feature: string, need: number, unit: string, have: number) =>
      `${feature} unlocks at ${need} ${unit} — you have ${have}.`,
    defaultCta: "Open the Ledger →",
    importCta: "…or import your Letterboxd history →",
  },
  common: {
    navCovenant: "NAV never falls. Watching adds; low ratings never subtract.",
    availUnknown: "Availability unknown (≠ unavailable)",
    errorLoad: "Couldn't load — retry",
    retry: "Retry",
    ageFresh: "Fresh",
    ageAging: (d: number) => `Aging ${d}d`,
    ageStale: (d: number) => `Stale ${d}d`,
    verdictFind: "Find",
    verdictAligned: "Aligned",
    verdictLetdown: "Letdown",
    resortedClient: "re-sorted client-side",
    showAll: "Show all",
    loadMore: "Load more",
  },
  /** Honest empty states per instrument (spec §3.x — unlock numbers stay explicit). */
  empty: {
    desk: "No log yet — tap a star above to open your position.",
    screener: "The screener needs a sample of your taste — rate 3 films ★3.5+ and candidates appear with reasons.",
    slate: "Your slate is empty — Keep films from the Screener and they queue here.",
    ledger: "No entries yet — find a film above and tap a star. Rating implies seen.",
    holdings: "No holdings — mark films Seen and they appear as positions.",
    performance: (n: number) => `NAV forms at 8 seen films — you're at ${n}. Every film only adds.`,
    coverage: "Coverage begins with your first seen film in any lineage.",
    auteurs: "Mark films Seen and directors appear with completion bars.",
    locations: "No located films yet — your map begins with your first seen film that has location data.",
    signature: (n: number) => `A signature forms from loved films (★4.5+) — you have ${n} of 8.`,
    lensEntities: "No published entities cross your films yet — every film you log can bring its theory here.",
    lensReadings: "No published readings on your films yet.",
    shelf: "Your shelf holds anything — films, tropes, misreadings, figures. Pin from any page.",
    takes: "No takes yet. Write your first reading — your own words are the strongest taste signal (×1.5).",
    masquerade: (n: number) => `Masquerade opens at 8 loved films — you have ${n}.`,
  },
} as const;
