import Link from "next/link";

/**
 * Provenance — per-page byline. We don't credit individual authors (like TV Tropes);
 * instead each page states how it was generated, when, and who is the accountable
 * editor (Wonwoo Yoon). This is an E-E-A-T / transparency signal, not crowd authorship.
 */
function fmt(d?: string | null): string | null {
  if (!d) return null;
  const t = new Date(d);
  if (isNaN(t.getTime())) return null;
  return t.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

export default function Provenance({ created, updated }: { created?: string | null; updated?: string | null }) {
  const c = fmt(created);
  const u = fmt(updated);
  return (
    <div className="provenance">
      Generated by the <span className="prov-by">Metatake</span> editorial method (AI-drafted)
      {c ? <> · created {c}</> : null}
      {u && u !== c ? <> · updated {u}</> : null}
      {" · "}editor <Link href="/editor">Wonwoo Yoon</Link>
      {" · "}<Link href="/methodology">how this is made</Link>
    </div>
  );
}
