import Link from "next/link";
import MethodologyBadge from "./MethodologyBadge";
import { t, DEFAULT_LOCALE, type Locale } from "@/lib/i18n";

/**
 * Provenance — per-page byline. We don't credit individual authors (like TV Tropes);
 * instead each page states how it was generated, when, and who is the accountable
 * editorial desk (led by Wonwoo Yoon). This is an E-E-A-T / transparency signal.
 */
function fmt(d?: string | null): string | null {
  if (!d) return null;
  const t = new Date(d);
  if (isNaN(t.getTime())) return null;
  return t.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

export default function Provenance({ created, updated, locale = DEFAULT_LOCALE }: { created?: string | null; updated?: string | null; locale?: Locale }) {
  const c = fmt(created);
  const u = fmt(updated);
  return (
    <div className="provenance">
      {t(locale, "Generated by the ")}<span className="prov-by">Metatake</span>{t(locale, " editorial method")}
      {c ? <> · {t(locale, "created {c}", { c })}</> : null}
      {u && u !== c ? <> · {t(locale, "updated {u}", { u })}</> : null}
      {" · "}{t(locale, "editorial desk led by ")}<Link href="/editor">Wonwoo Yoon</Link>
      {" · "}<Link href="/methodology">{t(locale, "how this is made")}</Link>
      <MethodologyBadge />
    </div>
  );
}
