import { Metadata } from "next";
import { unstable_cache } from "next/cache";
import { notFound } from "next/navigation";
import Link from "next/link";
import { createClient } from "@supabase/supabase-js";
import SiteNav from "@/components/home2/SiteNav";
import FilmTabBar from "@/components/FilmTabBar";
import PosterActions from "@/components/PosterActions";
import SaveChip from "@/components/SaveChip";
import FilmTopInfo from "@/components/FilmTopInfo";
import AccessCountryProvider from "@/components/AccessCountryProvider";
import AccessEnrichment, { type AccessRecord } from "@/components/AccessEnrichment";
import AccessSummary from "@/components/AccessSummary";
import accessEnrichment from "@/lib/access_enrichment.json";
import FilmLineageSection from "@/components/FilmLineageSection";
import CinecodexPanel, { type Codex, type FilmSubscores } from "@/components/CinecodexPanel";
import FilmRecommendedBy from "@/components/FilmRecommendedBy";
import InviteVideo from "@/components/InviteVideo";
import FilmHeroReel from "@/components/FilmHeroReel";
import LightboxImage from "@/components/LightboxImage";
import YouTubeFacade from "@/components/YouTubeFacade";
import EntityMap from "@/components/EntityMap";
import FilmMap from "@/components/FilmMap";
import EntityActions from "@/components/EntityActions";
import MovieListActions from "@/components/MovieListActions";
import SeqNav from "@/components/SeqNav";
import Provenance from "@/components/Provenance";
import Byline from "@/components/Byline";
import { fw, fwOrder, FAMILIES } from "@/lib/frameworks";
import { CRAFTS, personSlug } from "@/app/credits/credits-logic";
import { filmKeyCrew } from "@/lib/filmCrew";
import { axisLabel, nodeHref } from "@/lib/catalog";
import { pageRobots } from "@/lib/seo";
import { FILM_LOCATIONS_MIN, mergeCells, mergePins, type GeoPin } from "@/lib/atlas";
import { honorText, loadLineageListMeta } from "@/lib/lineage";
import { relatedForTier2Film, slugifyGenre } from "@/lib/related";
import RelatedBoxes from "@/components/RelatedBoxes";

export const revalidate = 300;
export async function generateStaticParams() { return []; }
const IMG = "https://image.tmdb.org/t/p";

function db() {
  return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
}

interface Props { params: Promise<{ slug: string }>; }

// Where-to-Watch enrichment (Phase A-lite): verified records live in lib/access_enrichment.json,
// bundled at build time (regenerated by worker/access-enrich-build.py). Keyed by tmdb_id.
function accessRecordFor(tmdbId: number | null | undefined): AccessRecord | null {
  if (!tmdbId) return null;
  const films = (accessEnrichment as unknown as { films: Record<string, AccessRecord> }).films;
  return films[String(tmdbId)] ?? null;
}

const KIND_LABEL: Record<string, string> = {
  character: "Characters", object: "Objects & symbols", location: "Locations",
  form: "Form & technique", trope: "Themes & motifs", title: "Title", film: "The film itself",
};
const KIND_ORDER = ["film", "character", "object", "location", "form", "trope", "title"];

type Fig = { id: string; kind: string | null; label: string; slug: string | null; description: string | null };
type FigRef = { label: string; slug: string | null };
type FilmLink = { slug: string; title: string; figs: FigRef[]; takeTitle: string | null; takeHref: string | null };
type MediaRow = { id: string; kind: string; source: string; external_id: string; url: string; thumbnail_url: string | null; title: string | null; attribution: string | null };
type TakeRow = { id: string; figure_id: string; framework: string | null; take_title: string | null; rationale: string | null; leap: string | null; strength: number | null; is_invitation: boolean | null; trope_id: string | null };
type SM = { id: string; framework: string | null; take_title: string | null; thesis: string | null; leap: string | null; strength: number | null; figLabel: string; figSlug: string | null };
type ArchRow = { axis: string; slug: string; label: string; n: number; fig_label: string | null; fig_slug: string | null };
type RcpRow = { kind: string; outlet: string; critic: string | null; year: number | null; tier: string; headline: string; comment: string; verdict: string | null; url: string };
type WnRow = { pos: number; rec_title: string; rec_year: number | null; rec_director: string | null; reason: string; target_slug: string | null; target_title: string | null; target_year: number | null; target_poster: string | null; tmdb_id: number | null; poster_path: string | null };
type WwPoint = { label?: string; text: string };
type WwLens = { key: string; points: WwPoint[] };
type RevRow = { source_slug: string; source_title: string; source_year: number | null };
type Ratings = { imdb_rating: number | null; imdb_votes: number | null; metascore: number | null; rt_tomatometer: number | null };
type WatchProv = { provider_id: number; provider_name: string; logo_path: string | null };
type WatchCountry = { link?: string; flatrate?: WatchProv[]; rent?: WatchProv[]; buy?: WatchProv[]; free?: WatchProv[]; ads?: WatchProv[] };
type Watch = { results: Record<string, WatchCountry>; countries: string[] };
type LinRow = { facet: string; list_slug: string; list_label: string; parent_label: string | null; result: string | null; rank: number | null; edition_year: number | null; rank_max: number | null; rep_type: string | null };
type QRow = { slug: string; title: string; display_title: string | null; title_spoiler: boolean | null; spoiler_level: string | null; question_type: string | null };
// Human phrasing — the CSS uppercases these anyway; the raw system keys
// ("AUTEUR_VISION") used to leak into the page and read as machine output.
const WW_TITLE: Record<string, string> = { auteur_vision: "The auteur's vision", aesthetic_innovation: "Aesthetic innovation", technical_mastery: "Technical mastery", philosophical_inquiry: "Philosophical inquiry", cinematic_lineage: "Cinematic lineage", spatial_aesthetics: "Space & place", critical_reception: "Critical reception", context_discourse: "Context & discourse" };

type CpSide = { take: string | null; figure: string | null; figureLabel: string | null } | null;
type CpRow = {
  sim: number;
  film: { slug: string; title: string; year: number | null; director: string | null };
  trope: { slug: string; title: string };
  here: CpSide;
  there: CpSide;
};

async function loadUncached(slug: string) {
  const supabase = db();
  const { data: film } = await supabase
    .from("films")
    .select("id, title, original_title, slug, year, director, director_slug, genres, poster_path, backdrop_path, tagline, runtime, release_date, certification, overview, imdb_id, tmdb_id, wikidata_id, tmdb_extra, created_at, visible, is_analyzed")
    .eq("slug", slug).maybeSingle();
  if (!film) return null;
  if (film.is_analyzed === false) {
    // Tier-2 catalog record: still surface the ambient data we DO have (no figures/readings).
    const [{ data: lnRows }, { data: revRows }, { data: ratRow }, { data: wpRow }] = await Promise.all([
      supabase.rpc("film_lineage_for", { p_film_id: film.id }),
      supabase.rpc("film_next_reverse", { p_film_id: film.id }),
      supabase.from("film_ratings").select("imdb_rating, imdb_votes, metascore, rt_tomatometer").eq("film_id", film.id).maybeSingle(),
      supabase.from("film_watch_providers").select("results, countries").eq("film_id", film.id).maybeSingle(),
    ]);
    const mLineage = (lnRows ?? []) as LinRow[];
    // Per-list source/QID for the Lineage section's citation tags.
    const mListMeta = Object.fromEntries(await loadLineageListMeta([...new Set(mLineage.map((l) => l.list_slug))]));
    return {
      minimal: true as const, film,
      lineage: mLineage,
      lnListMeta: mListMeta,
      recommendedBy: (revRows ?? []) as RevRow[],
      ratings: (ratRow as Ratings | null) ?? null,
      watch: (wpRow as Watch | null) ?? null,
    };
  }

  const [{ data: figRows }, { data: aff }, { data: mediaRows }, { data: catRows }, { data: rcpRows }, { data: wnRows }, { data: waRows }, { data: revRows }, { data: lnRows }, { data: ratRow }, { data: wpRow }, { data: qRows }, { data: cpJson }] = await Promise.all([
    supabase.from("figures").select("id, kind, label, slug, description").eq("film_id", film.id).eq("status", "approved"),
    supabase.from("film_affinities").select("related_film_id, score, shared_meta_take_ids, cos, updated_at").eq("film_id", film.id).order("score", { ascending: false }).limit(5),
    supabase.from("media").select("id, kind, source, external_id, url, thumbnail_url, title, attribution")
      .eq("entity_type", "film").eq("entity_id", film.id).eq("status", "published").order("position"),
    supabase.rpc("film_catalog", { p_film_id: film.id }),
    supabase.rpc("film_reception", { p_film_id: film.id }),
    supabase.rpc("film_next", { p_film_id: film.id }),
    supabase.rpc("film_asset", { p_film_id: film.id }),
    supabase.rpc("film_next_reverse", { p_film_id: film.id }),
    supabase.rpc("film_lineage_for", { p_film_id: film.id }),
    supabase.from("film_ratings").select("imdb_rating, imdb_votes, metascore, rt_tomatometer").eq("film_id", film.id).maybeSingle(),
    supabase.from("film_watch_providers").select("results, countries").eq("film_id", film.id).maybeSingle(),
    supabase.from("questions").select("slug, title, display_title, title_spoiler, spoiler_level, question_type")
      .eq("film_id", film.id).eq("status", "published").order("published_at", { ascending: false }),
    supabase.rpc("film_counterpoints", { p_slug: slug, p_n: 6 }),
  ]);
  const archetypes = (catRows ?? []) as ArchRow[];
  const reception = (rcpRows ?? []) as RcpRow[];
  const watchNext = (wnRows ?? []) as WnRow[];
  const whyWatch = (Array.isArray(waRows) ? waRows : []) as WwLens[];
  const recommendedBy = (revRows ?? []) as RevRow[];
  const lineage = (lnRows ?? []) as LinRow[];
  // Per-list source/QID for the Lineage section's citation tags.
  const lnListMeta = Object.fromEntries(await loadLineageListMeta([...new Set(lineage.map((l) => l.list_slug))]));
  const ratings = (ratRow as Ratings | null) ?? null;
  const watch = (wpRow as Watch | null) ?? null;
  const questions = (qRows ?? []) as QRow[];

  const figures = (figRows ?? []) as Fig[];
  const figById = new Map<string, Fig>(figures.map((f) => [f.id, f]));
  const figIds = figures.map((f) => f.id);

  // Strong Misreadings (new model) — published takes anchored to this film's figures.
  let invitation: string | null = null;
  const misreadings: SM[] = [];
  const takeCount = new Map<string, number>();
  // trope_id → this film's own reading of that trope (title + carrying figure).
  const tropeTake = new Map<string, { title: string; figSlug: string | null; strength: number; takeId: string }>();
  if (figIds.length) {
    const { data: takeRows } = await supabase
      .from("takes")
      .select("id, figure_id, framework, take_title, rationale, leap, strength, is_invitation, trope_id")
      .in("figure_id", figIds).eq("status", "published");
    for (const t of (takeRows ?? []) as TakeRow[]) {
      if (t.is_invitation) { if (!invitation) invitation = t.rationale; continue; }
      const f = figById.get(t.figure_id);
      misreadings.push({ id: t.id, framework: t.framework, take_title: t.take_title, thesis: t.rationale, leap: t.leap, strength: t.strength, figLabel: f?.label ?? "", figSlug: f?.slug ?? null });
      takeCount.set(t.figure_id, (takeCount.get(t.figure_id) ?? 0) + 1);
      // Per-trope: THIS film's reading title (strongest take wins; ties → take id, deterministic).
      if (t.trope_id && t.take_title) {
        const cur = tropeTake.get(t.trope_id);
        const s = t.strength ?? 0;
        if (!cur || s > cur.strength || (s === cur.strength && t.id < cur.takeId)) {
          tropeTake.set(t.trope_id, { title: t.take_title, figSlug: f?.slug ?? null, strength: s, takeId: t.id });
        }
      }
    }
  }
  misreadings.sort((a, b) => fwOrder(a.framework) - fwOrder(b.framework));

  // Tropes (kind='figure_type') — cross-film types this film's figures belong to.
  const figRefById = new Map<string, FigRef>(figures.map((f) => [f.id, { label: f.label, slug: f.slug }]));
  let tropes: FilmLink[] = [];
  if (figIds.length) {
    const { data: ftm } = await supabase.from("figure_type_members").select("meta_take_id, figure_id").in("figure_id", figIds);
    const mtIds = [...new Set((ftm ?? []).map((r) => r.meta_take_id))];
    if (mtIds.length) {
      const { data: tms } = await supabase.from("meta_takes").select("id, slug, title").in("id", mtIds).eq("status", "published").eq("kind", "figure_type");
      const tmMap = new Map((tms ?? []).map((m) => [m.id, m]));
      const tFigs = new Map<string, FigRef[]>();
      for (const r of (ftm ?? [])) {
        if (!tmMap.has(r.meta_take_id)) continue;
        const fg = figRefById.get(r.figure_id); if (!fg) continue;
        const arr = tFigs.get(r.meta_take_id) ?? [];
        if (!arr.some((x) => x.label === fg.label)) arr.push(fg);
        tFigs.set(r.meta_take_id, arr);
      }
      tropes = [...tFigs.entries()].map(([id, figs]) => {
        const m = tmMap.get(id)!;
        const bt = tropeTake.get(id);
        return {
          slug: m.slug, title: m.title, figs,
          takeTitle: bt?.title ?? null,
          takeHref: bt?.figSlug ? `/film/${film.slug}/figure/${bt.figSlug}` : null,
        };
      })
        .sort((a, b) => b.figs.length - a.figs.length || a.title.localeCompare(b.title));
    }
  }

  const media = (mediaRows ?? []) as unknown as MediaRow[];
  const stills = media.filter((m) => m.kind === "image").slice(0, 5);
  const trailer = media.find((m) => m.kind === "video") ?? null;
  // Hero reel: all videos, clips first (title not "trailer/teaser") and trailer last.
  // media is already position-ordered, and Array.sort is stable, so order is preserved within groups.
  const isTrailerTitle = (t: string | null) => !!t && /trailer|teaser/i.test(t);
  const orderedVids = media.filter((m) => m.kind === "video").sort((a, b) => (isTrailerTitle(a.title) ? 1 : 0) - (isTrailerTitle(b.title) ? 1 : 0));
  const videos = orderedVids.map((m) => ({ id: m.external_id, title: m.title ?? "" }));
  const heroPoster = orderedVids[0]?.thumbnail_url ?? null;

  // Connected films — top-5 kin with their evidence (taste cosine + shared-trope count).
  const relIds = (aff ?? []).map((a) => a.related_film_id);
  const { data: relFilms } = relIds.length
    ? await supabase.from("films").select("id, title, slug, year, poster_path").in("id", relIds).eq("visible", true)
    : { data: [] as { id: string; title: string; slug: string; year: number | null; poster_path: string | null }[] };
  const relFilmMap = new Map((relFilms ?? []).map((f) => [f.id, f]));
  const recs = (aff ?? []).map((a) => {
    const f = relFilmMap.get(a.related_film_id);
    if (!f) return null;
    return {
      title: f.title, slug: f.slug, year: f.year, poster_path: f.poster_path,
      cos: a.cos == null ? null : Number(a.cos),
      sharedN: ((a.shared_meta_take_ids ?? []) as string[]).length,
    };
  }).filter(Boolean) as { title: string; slug: string; year: number | null; poster_path: string | null; cos: number | null; sharedN: number }[];
  const recsUpdated = (aff ?? []).reduce<string | null>((m, a) => {
    const u = (a as { updated_at?: string }).updated_at ?? null;
    return u && (!m || u > m) ? u : m;
  }, null);
  const counterpoints = (Array.isArray(cpJson) ? cpJson : []) as CpRow[];

  const { data: geoRows } = await supabase.rpc("film_geo", { p_slug: slug });
  const geoCount = Array.isArray(geoRows) ? geoRows.length : 0;
  // geoCells gates the Locations tab/link (the read page's own 404 rule and
  // the sitemap SQL count the same cells); geoMerged is the fused display count.
  const geoCells = Array.isArray(geoRows) ? mergeCells(geoRows as GeoPin[]).length : 0;
  const geoMerged = Array.isArray(geoRows) ? mergePins(geoRows as GeoPin[]).length : 0;

  // takeCount is a Map; the Data Cache (unstable_cache) can't serialize Maps,
  // so return it as a plain object. Consumers read it with bracket access.
  return { film, figures, takeCount: Object.fromEntries(takeCount), invitation, misreadings, tropes, recs, recsUpdated, counterpoints, stills, trailer, videos, heroPoster, archetypes, reception, watchNext, whyWatch, recommendedBy, lineage, lnListMeta, ratings, watch, geoCount, geoCells, geoMerged, questions };
}

// The full film load is ~20 Supabase round-trips and generateStaticParams
// returns [] (nothing prebuilt), so without caching every film view re-ran the
// whole query set dynamically. Cache the result per slug in the Data Cache so
// the route becomes ISR-cached; tagged film:<slug> for on-demand refresh.
function load(slug: string) {
  // Cache key bumped (load4) when lnListMeta joined the payload — the
  // Data Cache outlives deploys, so a shape change needs a new key.
  return unstable_cache(() => loadUncached(slug), ["film-load4", slug], {
    revalidate: 300,
    tags: [`film:${slug}`],
  })();
}

// The page-chrome RPCs (movements + TakeScore) were also uncached, which on
// their own would keep the route dynamic — cache them per slug as well.
// cinecodex_film_subscores adds per-dimension percentiles vs all scored films
// (one indexed lookup + one aggregate pass; null for unscored films).
function loadChrome(slug: string) {
  // Cache key bumped (film-chrome2) when subscores joined the payload — the
  // Data Cache outlives deploys, so a shape change needs a new key.
  return unstable_cache(
    async () => {
      const supabase = db();
      const [{ data: mvRows }, { data: codexRow }, { data: subRow }] = await Promise.all([
        supabase.rpc("film_movements", { p_slug: slug }),
        supabase.rpc("cinecodex_for", { p_slug: slug }),
        supabase.rpc("cinecodex_film_subscores", { p_slug: slug }),
      ]);
      return {
        movements: (mvRows as { slug: string; label: string; kind: string; country_code: string | null }[] | null) ?? [],
        codex: (codexRow as Codex | null),
        subscores: (subRow as FilmSubscores | null),
      };
    },
    ["film-chrome2", slug],
    { revalidate: 300, tags: [`film:${slug}`] },
  )();
}

// Tier-2 "keep reading" modules (lib/related.ts recipe) — cached per slug like
// the main load, so the catalog route stays ISR-cached.
function loadTier2Related(slug: string, args: {
  filmId: string; filmSlug: string; filmTitle: string; year: number | null;
  director: string | null; directorSlug: string | null;
  genres: string[] | null; lineageListSlugs: string[];
}) {
  return unstable_cache(() => relatedForTier2Film(args), ["film-t2-related", slug], {
    revalidate: 300,
    tags: [`film:${slug}`],
  })();
}

// order + cap for the film-page Archetype section
const ARCH_ORDER = ["object", "char_archetype", "char_identity", "char_complex", "location", "theme"];
const ARCH_CAP: Record<string, number> = { theme: 12, char_identity: 18 };

// Builds a clean, spoiler-free meta description from the invitation prose:
// strips markdown/newlines, keeps the first 1-2 sentences, truncates at
// <=155 chars on a word boundary with an ellipsis if cut.
function descriptionFromInvitation(invitation: string): string | null {
  const plain = invitation
    .replace(/[*_`>#[\]]/g, "")
    .replace(/\s+/g, " ")
    .trim();
  if (!plain) return null;
  // Split only where a sentence end is followed by a capital/quote, so
  // abbreviations like "(b. 1958)" or "Dr. Strangelove" don't end a sentence.
  const sentences = plain.split(/(?<=[.!?])\s+(?=["'“A-Z])/);
  let text = "";
  for (const s of sentences) {
    const next = text ? `${text} ${s}` : s;
    if (text.length >= 60 && next.length > 155) break;
    text = next;
    if (text.length >= 80) break;
  }
  if (!text) text = plain;
  if (text.length <= 155) return text;
  const cut = text.slice(0, 154);
  const lastSpace = cut.lastIndexOf(" ");
  const trimmed = (lastSpace > 0 ? cut.slice(0, lastSpace) : cut).trim();
  return `${trimmed}…`;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const data = await load(slug);
  if (!data) return { title: "Not found" };
  if ("minimal" in data && data.minimal) {
    // Full catalog-record head: Tier-1's pattern minus the analysis claim —
    // no readings exist yet, so the title promises cast/watch/context only.
    const f = data.film as { title: string; original_title: string | null; year: number | null; director: string | null; genres: string[] | null; overview: string | null };
    const native = f.original_title && f.original_title !== f.title ? ` (${f.original_title})` : "";
    const title = `${f.title}${f.year ? ` (${f.year})` : ""} — Cast, Where to Watch & Context`;
    const fromOverview = f.overview ? descriptionFromInvitation(f.overview) : null;
    const formula = [
      `${f.title}${native}${f.year ? ` (${f.year})` : ""}`,
      f.director ? `directed by ${f.director}` : null,
    ].filter(Boolean).join(", ")
      + (f.genres?.length ? ` — ${f.genres.slice(0, 3).join(", ")}.` : ".")
      + " Cast, context and where to watch on Metatake.";
    const description = fromOverview ?? formula;
    return {
      title,
      description,
      openGraph: { title, description },
      twitter: { card: "summary_large_image", title, description },
      alternates: { canonical: `/film/${slug}` },
      robots: pageRobots(false),
    };
  }
  const meetsBar = data.figures.length >= 3 && (data.film as { visible?: boolean }).visible !== false;
  const title = `${data.film.title}${data.film.year ? ` (${data.film.year})` : ""} — Analysis, Themes & Symbols`;
  const templatedDescription = data.misreadings.length
    ? `${data.film.title} read closely: ${data.figures.length} figures and ${data.misreadings.length} strong misreadings across 14 critical frameworks.`
    : undefined;
  const fromInvitation = data.invitation ? descriptionFromInvitation(data.invitation) : null;
  // A mid-sentence cut ("…") reads as a broken sentence in search snippets, so a
  // truncated extraction only ships when there is no complete-sentence fallback.
  const picked = fromInvitation && (!fromInvitation.endsWith("…") || !templatedDescription)
    ? fromInvitation
    : templatedDescription;
  // Numbers are a CTR signal — append the corpus counts when the prose
  // description has room (the templated fallback already carries them).
  const stats = ` ${data.figures.length} figures · ${data.misreadings.length} readings inside.`;
  const description = picked && picked === fromInvitation && data.misreadings.length && (picked + stats).length <= 168
    ? picked + stats
    : picked;
  return {
    title,
    ...(description ? { description } : {}),
    openGraph: { title, ...(description ? { description } : {}) },
    twitter: { card: "summary_large_image", title, ...(description ? { description } : {}) },
    alternates: { canonical: `/film/${slug}` },
    robots: pageRobots(meetsBar),
  };
}

export default async function FilmPage({ params }: Props) {
  const { slug } = await params;
  const data = await load(slug);
  if (!data) notFound();
  const { movements, codex, subscores } = await loadChrome(slug);
  const crew = (data.film as { tmdb_id?: number | null }).tmdb_id ? await filmKeyCrew((data.film as { tmdb_id: number }).tmdb_id) : [];
  const _cx = codex;
  const codexBadge = _cx ? (
    <a className="df-mts" href="#df-codex" title="TakeScore — durable value minus risk. Click for the full breakdown.">
      <span className="df-mts-n">{Math.round(_cx.v - _cx.r)}</span>
      <span className="df-mts-l"><b>TakeScore</b><i>value {Math.round(_cx.v)} · cost {Math.round(_cx.c)} · risk {Math.round(_cx.r)}</i></span>
    </a>
  ) : null;
  const mvChips = movements.length ? (
    <div className="df-movements">
      {movements.map((m) => (
        <Link key={m.slug} className={`df-mv${m.kind === "movement" ? " df-mv--mov" : ""}`} href={`/movements/${m.slug}`}>{m.label}</Link>
      ))}
    </div>
  ) : null;
  if ("minimal" in data && data.minimal) {
    const f = data.film as {
      id: string; title: string; original_title: string | null; slug: string; year: number | null;
      director: string | null; director_slug: string | null; genres: string[] | null;
      poster_path: string | null; backdrop_path: string | null; tagline: string | null;
      overview: string | null; runtime: number | null; release_date: string | null;
      certification: string | null; imdb_id: string | null; tmdb_id: number | null; wikidata_id: string | null;
    };
    const { lineage, lnListMeta, recommendedBy, ratings, watch } = data;
    const mAccessRec = accessRecordFor(f.tmdb_id);
    // "Keep reading" modules + the director-hub slug: a Tier-2 row often lacks
    // director_slug even when the hub exists on a visible sibling — the recipe
    // surfaces whichever sibling carries it. Auteur lists are excluded from
    // the tradition source (the director module already owns that shelf).
    const { sections: t2Sections, directorHubSlug } = await loadTier2Related(slug, {
      filmId: f.id, filmSlug: f.slug, filmTitle: f.title, year: f.year,
      director: f.director, directorSlug: f.director_slug, genres: f.genres,
      lineageListSlugs: lineage.filter((l) => l.facet !== "auteur").map((l) => l.list_slug),
    });
    const dirSlug = f.director_slug ?? directorHubSlug;
    // Native-script title, mirroring how director/credits pages show native names.
    const nativeTitle = f.original_title && f.original_title !== f.title ? f.original_title : null;
    const mRuntime = f.runtime ? `${f.runtime} min` : null;
    const mCert = f.certification ? f.certification.replace(/^[A-Z]{2}:/, "") : null;
    const hasInfo = !!(f.overview || f.release_date || mRuntime || f.genres?.length || mCert || nativeTitle);
    const mSameAs = [
      f.imdb_id ? `https://www.imdb.com/title/${f.imdb_id}/` : null,
      f.wikidata_id ? `https://www.wikidata.org/wiki/${f.wikidata_id}` : null,
    ].filter(Boolean);
    const mJsonld = {
      "@context": "https://schema.org", "@type": "Movie", "@id": `https://metatake.net/film/${f.slug}`, name: f.title,
      ...(nativeTitle ? { alternateName: nativeTitle } : {}),
      ...(f.release_date ? { datePublished: f.release_date } : f.year ? { datePublished: String(f.year) } : {}),
      ...(f.genres?.length ? { genre: f.genres } : {}),
      ...(f.runtime ? { duration: `PT${f.runtime}M` } : {}),
      ...(f.director ? { director: { "@type": "Person", name: f.director } } : {}),
      ...(f.poster_path ? { image: `${IMG}/w500${f.poster_path}` } : {}),
      ...(f.overview ? { description: f.overview } : {}),
      ...(mSameAs.length ? { sameAs: mSameAs } : {}),
    };
    const mBreadcrumbLd = {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: "https://metatake.net" },
        { "@type": "ListItem", position: 2, name: "Films", item: "https://metatake.net/film" },
        { "@type": "ListItem", position: 3, name: `${f.title}${f.year ? ` (${f.year})` : ""}`, item: `https://metatake.net/film/${f.slug}` },
      ],
    };
    const mTabs = ([
      hasInfo ? { id: "df-information", label: "About" } : null,
      codex ? { id: "df-codex", label: "TakeScore" } : null,
      lineage.length ? { id: "df-lineage", label: "Lineage" } : null,
      recommendedBy.length ? { id: "df-recby", label: "Recommended by" } : null,
      crew.length
        ? { id: "df-crew", label: "Credits" }
        : f.tmdb_id ? { id: "df-credits", label: "Credits", href: `/credits?f=${f.tmdb_id}` } : null,
      { id: "df-watch", label: "Where to watch" },
      f.poster_path ? { id: "gallery", label: "Gallery", href: `/film/${f.slug}/gallery` } : null,
    ].filter(Boolean)) as { id: string; label: string; href?: string }[];
    return (
      <div className="mt">
        <SiteNav />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(mJsonld) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(mBreadcrumbLd) }} />
        <div className="df-wrap">
          <div className="df-crumb">
            <Link href="/film">Films</Link>
            {f.director && dirSlug ? <><span className="df-sep">›</span><Link href={`/director/${dirSlug}`}>{f.director}</Link></> : null}
          </div>
          <section className="df-hero">
            {f.backdrop_path ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img className="df-backdrop" src={`${IMG}/w780${f.backdrop_path}`} alt={`${f.title} backdrop`} width={780} height={439} />
            ) : <div className="df-backdrop df-backdrop--empty" aria-hidden="true" />}
            <div className="df-headrow">
              {f.poster_path ? (
                <LightboxImage
                  src={`${IMG}/w342${f.poster_path}`} fullUrl={`${IMG}/w500${f.poster_path}`}
                  alt={`${f.title} poster`} className="df-poster" caption={f.title}
                  width={342} height={513} fetchPriority="high"
                />
              ) : <div className="df-poster df-poster--empty" aria-hidden="true" />}
              <div className="df-htxt">
                <h1>
                  {f.title} <span className="df-yr">({f.year ?? "?"})</span>
                  {nativeTitle ? <span style={{ fontWeight: 400, opacity: 0.72, fontSize: "0.72em" }}> ({nativeTitle})</span> : null}
                </h1>
                {f.tagline ? <div className="df-tagline">{f.tagline}</div> : null}
                <div className="df-facts">
                  {f.director ? (dirSlug ? <Link href={`/director/${dirSlug}`}>{f.director}</Link> : <span>{f.director}</span>) : null}
                  {f.genres?.length ? <><span className="df-d" />{f.genres.slice(0, 3).map((g, i) => (
                    <span key={g}>{i > 0 ? " · " : ""}<Link href={`/genre/${slugifyGenre(g)}`}>{g}</Link></span>
                  ))}</> : null}
                  {mRuntime ? <><span className="df-d" />{mRuntime}</> : null}
                  {mCert ? <><span className="df-d" />{mCert}</> : null}
                </div>
                {codexBadge}
                {mvChips}
                <div className="df-hactions">
                  <MovieListActions filmId={f.id} />
                  {f.tmdb_id ? <Link className="df-like" href={`/credits?f=${f.tmdb_id}`}>🎞 Follow the credits →</Link> : null}
                  {f.poster_path ? <Link className="df-like" href={`/film/${f.slug}/gallery`}>🖼 Gallery →</Link> : null}
                </div>
                <p className="df-catnote">Catalog entry — not yet deeply analyzed on Metatake. Track it in your lists; the films most readers add are the ones we analyze next.</p>
              </div>
            </div>
          </section>

          <AccessCountryProvider>
            <FilmTopInfo ratings={ratings} watch={watch} imdbId={f.imdb_id} />

          {mTabs.length > 1 ? <FilmTabBar tabs={mTabs} /> : null}

          {/* ABOUT — overview + the ambient facts we hold. original_title/overview
              are being backfilled from TMDB: every field is null-safe, so this
              section lights up as the data lands. */}
          {hasInfo ? (
            <section className="df-sec" id="df-information">
              <h2 className="df-h2">About {f.title}</h2>
              {f.overview ? <p className="df-ov">{f.overview}</p> : null}
              <dl className="df-dl">
                {f.director ? <><dt>Director</dt><dd>{dirSlug ? <Link href={`/director/${dirSlug}`}>{f.director}</Link> : f.director}</dd></> : null}
                {nativeTitle ? <><dt>Original title</dt><dd>{nativeTitle}</dd></> : null}
                {f.release_date ? <><dt>Released</dt><dd>{f.release_date}</dd></> : null}
                {mRuntime ? <><dt>Runtime</dt><dd>{mRuntime}</dd></> : null}
                {f.genres?.length ? <><dt>Genre</dt><dd>{f.genres.map((g, i) => (
                  <span key={g}>{i > 0 ? ", " : ""}<Link href={`/genre/${slugifyGenre(g)}`}>{g}</Link></span>
                ))}</dd></> : null}
                {mCert ? <><dt>Rated</dt><dd>{mCert}</dd></> : null}
              </dl>
            </section>
          ) : null}

          <CinecodexPanel data={codex as Codex | null} title={f.title} />
          <FilmLineageSection lineage={lineage} title={f.title} slug={f.slug} listMeta={lnListMeta} movements={movements} />
          <FilmRecommendedBy rows={recommendedBy} title={f.title} />

          {/* CREDITS — the same crawlable key-craft block Tier-1 carries */}
          {crew.length > 0 ? (
            <section className="df-sec" id="df-crew">
              <h2 className="df-h2">Credits — who made {f.title}</h2>
              <p className="df-sub">The key crafts behind the film. Each name opens their body of work: the directors they keep returning to, and where their films are read on Metatake.</p>
              <div className="rcp-list">
                {f.director ? (
                  <div className="rcp-row">
                    <span className="rcp-m" style={{ minWidth: 150 }}>Director</span>
                    {dirSlug ? <Link className="rcp-h" href={`/director/${dirSlug}`}>{f.director}</Link> : <span className="rcp-h">{f.director}</span>}
                  </div>
                ) : null}
                {crew.map((c) => (
                  <div key={c.craft} className="rcp-row">
                    <span className="rcp-m" style={{ minWidth: 150 }}>{CRAFTS[c.craft].label}</span>
                    <span>
                      {c.people.map((pp, i) => (
                        <span key={pp.id}>
                          {i > 0 ? ", " : ""}
                          <Link className="rcp-h" href={`/credits/${personSlug(pp.name, pp.id)}`}>{pp.name}</Link>
                        </span>
                      ))}
                    </span>
                  </div>
                ))}
              </div>
              {f.tmdb_id ? (
                <div className="df-src"><Link href={`/credits?f=${f.tmdb_id}`}>Open in the interactive Credits explorer →</Link> · Credits data from TMDB</div>
              ) : null}
            </section>
          ) : null}

          <section className="df-sec" id="df-watch">
            <AccessSummary watch={watch} record={mAccessRec} slug={f.slug} title={f.title} />
            {mAccessRec ? <AccessEnrichment record={mAccessRec} tmdbId={f.tmdb_id} /> : null}
          </section>
          </AccessCountryProvider>

          {/* KEEP READING — the funnel from this catalog record into worked content */}
          {t2Sections.map((s) => (
            <RelatedBoxes key={s.heading} heading={s.heading} variant={s.variant} boxes={s.boxes} />
          ))}

          <div className="df-src">Data &amp; images via TMDB. Not endorsed or certified by TMDB.</div>
        </div>
      </div>
    );
  }
  const { film, figures, takeCount, invitation, misreadings, tropes, recs, recsUpdated, counterpoints, stills, trailer, videos, heroPoster, archetypes, reception, watchNext, whyWatch, recommendedBy, lineage, lnListMeta, ratings, watch, geoCount, geoCells, geoMerged, questions } = data;
  const reviews = reception.filter((r) => r.kind === "criticism");
  const papers = reception.filter((r) => r.kind === "academic");
  const hasLineage = lineage.length > 0;

  // Figures shown in the catalogue exclude the synthetic 'film'/'title' anchors.
  const catalogue = figures.filter((f) => f.kind !== "film" && f.kind !== "title" && (takeCount[f.id] ?? 0) > 0);
  const grouped = KIND_ORDER.filter((k) => k !== "film" && k !== "title")
    .map((k) => ({ kind: k, items: catalogue.filter((f) => (f.kind ?? "trope") === k) })).filter((g) => g.items.length > 0);

  const smByFamily = FAMILIES.map((fam) => ({ fam, items: misreadings.filter((m) => fw(m.framework).family === fam.key) })).filter((g) => g.items.length > 0);

  const extra = (film.tmdb_extra ?? {}) as { cast?: { name: string; character: string }[]; writers?: string[]; country?: string[]; original_language?: string; vote_average?: number; collection?: string | null };
  const cast = extra.cast ?? [];
  const runtimeFmt = film.runtime ? `${film.runtime} min` : null;
  const cert = film.certification ? film.certification.replace(/^[A-Z]{2}:/, "") : null;
  const country = extra.country?.length ? extra.country[0] : null;

  const archGroups = ARCH_ORDER
    .map((axis) => ({ axis, items: archetypes.filter((a) => a.axis === axis).slice(0, ARCH_CAP[axis] ?? 999) }))
    .filter((g) => g.items.length > 0);
  const filmInfoPresent = !!(film.overview || cast.length || extra.writers?.length || film.release_date || extra.country?.length || trailer);
  const accessRec = accessRecordFor(film.tmdb_id);
  const tabs = ([
    invitation ? { id: "df-invitation", label: "Invitation" } : null,
    whyWatch.length ? { id: "df-whywatch", label: "Why watch" } : null,
    codex ? { id: "df-codex", label: "TakeScore" } : null,
    geoCount > 0 ? { id: "df-atlas", label: "Atlas" } : null,
    geoCells >= FILM_LOCATIONS_MIN ? { id: "df-locations", label: "Locations", href: `/film/${film.slug}/locations` } : null,
    hasLineage ? { id: "df-lineage", label: "Lineage" } : null,
    recommendedBy.length ? { id: "df-recby", label: "Recommended by" } : null,
    misreadings.length ? { id: "df-readings", label: "Strong Misreadings!" } : null,
    grouped.length ? { id: "df-figures", label: "Figures" } : null,
    tropes.length ? { id: "df-tropes", label: "Tropes" } : null,
    { id: "df-map", label: "Connections" },
    archGroups.length ? { id: "df-archetype", label: "Archetype" } : null,
    reception.length ? { id: "df-reception", label: "Reception" } : null,
    questions.length ? { id: "df-curious", label: "Curious" } : null,
    watchNext.length ? { id: "df-watchnext", label: "Watch next" } : null,
    recs.length ? { id: "df-connected", label: "Films like" } : null,
    counterpoints.length ? { id: "df-counterpoints", label: "Counterpoints" } : null,
    filmInfoPresent ? { id: "df-information", label: "Information" } : null,
    { id: "df-watch", label: "Where to watch" },
    crew.length
      ? { id: "df-crew", label: "Credits" }
      : film.tmdb_id ? { id: "df-credits", label: "Credits", href: `/credits?f=${film.tmdb_id}` } : null,
    (film.backdrop_path || film.poster_path) ? { id: "df-gallery", label: "Gallery", href: `/film/${film.slug}/gallery` } : null,
  ].filter(Boolean)) as { id: string; label: string; href?: string }[];

  // Entity anchors (§8.2 film-entity recognition): canonical @id + external IDs.
  // Field set must stay consistent with /film/lineage/[slug]'s Movie node
  // (shared @id — contradictions suppress rich results; SEO_LINEAGE_SPEC §1b-2).
  const movieSameAs = [
    film.wikidata_id ? `https://www.wikidata.org/wiki/${film.wikidata_id}` : null,
    film.tmdb_id ? `https://www.themoviedb.org/movie/${film.tmdb_id}` : null,
    film.imdb_id ? `https://www.imdb.com/title/${film.imdb_id}/` : null,
  ].filter(Boolean);
  const wonHonors = lineage.filter((l) => l.result && l.result !== "listed" && l.facet !== "auteur");

  const jsonld = {
    "@context": "https://schema.org", "@type": "Movie", "@id": `https://metatake.net/film/${film.slug}`,
    url: `https://metatake.net/film/${film.slug}`, name: film.title,
    ...(film.release_date ? { datePublished: film.release_date } : film.year ? { datePublished: String(film.year) } : {}),
    ...(film.genres?.length ? { genre: film.genres } : {}),
    ...(film.runtime ? { duration: `PT${film.runtime}M` } : {}),
    ...(film.director ? { director: { "@type": "Person", name: film.director } } : {}),
    ...(cast.length ? { actor: cast.map((c) => ({ "@type": "Person", name: c.name })) } : {}),
    ...(film.poster_path ? { image: `${IMG}/w500${film.poster_path}` } : {}),
    ...(film.overview ? { description: film.overview } : {}),
    ...(movieSameAs.length ? { sameAs: movieSameAs } : {}),
    ...(wonHonors.filter((l) => l.result === "won").length
      ? { award: wonHonors.filter((l) => l.result === "won").map(honorText) }
      : {}),
    // TakeScore as a schema.org Review — Tier-1 + scored films only. ratingValue
    // must equal the TakeScore visibly rendered on the page (Google requires
    // correspondence): subscores.takescore == Math.round(v − r), the badge number.
    ...(codex && subscores ? {
      review: {
        "@type": "Review",
        author: { "@type": "Organization", name: "Metatake", url: "https://metatake.net" },
        name: "TakeScore",
        reviewRating: { "@type": "Rating", ratingValue: subscores.takescore, worstRating: -100, bestRating: 100 },
      },
    } : {}),
  };

  // Mirrors the visible trail (Films › director › film).
  const hasDirCrumb = !!(film.director && film.director_slug);
  const breadcrumbLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://metatake.net" },
      { "@type": "ListItem", position: 2, name: "Films", item: "https://metatake.net/film" },
      ...(hasDirCrumb ? [{ "@type": "ListItem", position: 3, name: film.director, item: `https://metatake.net/director/${film.director_slug}` }] : []),
      { "@type": "ListItem", position: hasDirCrumb ? 4 : 3, name: `${film.title}${film.year ? ` (${film.year})` : ""}`, item: `https://metatake.net/film/${film.slug}` },
    ],
  };

  // Page-level provenance (E-E-A-T): mirrors the figure page — the readings and the
  // invitation are editorial work, drafted in-house and signed by the human editor.
  const pageJsonld = {
    "@context": "https://schema.org", "@type": "WebPage",
    url: `https://metatake.net/film/${film.slug}`,
    name: `${film.title}${film.year ? ` (${film.year})` : ""} — Metatake`,
    about: { "@type": "Movie", name: film.title },
    author: { "@type": "Organization", "@id": "https://metatake.net/#org", name: "Metatake" },
    editor: { "@type": "Person", "@id": "https://metatake.net/editor#person", name: "Wonwoo Yoon", url: "https://metatake.net/editor" },
    publisher: { "@type": "Organization", "@id": "https://metatake.net/#org", name: "Metatake" },
    ...(film.created_at ? { datePublished: film.created_at } : {}),
  };

  return (
    <div className="mt">
      <SiteNav />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonld) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(pageJsonld) }} />
      <div className="df-wrap">
        <div className="df-crumb">
          <Link href="/film">Films</Link>
          {film.director_slug ? <><span className="df-sep">›</span><Link href={`/director/${film.director_slug}`}>{film.director}</Link></> : null}
        </div>

        {/* HERO — autoplay (muted) trailer in full 16:9; falls back to the colour backdrop */}
        <section className={`df-hero${videos.length ? " df-hero--vid" : ""}`}>
          {videos.length ? (
            <FilmHeroReel videos={videos} poster={heroPoster ?? undefined} start={7} />
          ) : film.backdrop_path ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img className="df-backdrop" src={`${IMG}/w780${film.backdrop_path}`} alt={`${film.title} backdrop`} width={780} height={439} />
          ) : <div className="df-backdrop df-backdrop--empty" aria-hidden="true" />}
          <div className="df-headrow">
            {film.poster_path ? (
              <LightboxImage
                src={`${IMG}/w342${film.poster_path}`} fullUrl={`${IMG}/w500${film.poster_path}`}
                alt={`${film.title} poster`} className="df-poster" caption={film.title}
                width={342} height={513} fetchPriority="high"
              />
            ) : <div className="df-poster df-poster--empty" aria-hidden="true" />}
            <div className="df-htxt">
              <h1>{film.title} <span className="df-yr">({film.year ?? "?"})</span></h1>
              {film.tagline ? <div className="df-tagline">{film.tagline}</div> : null}
              <Byline created={film.created_at} />
              <div className="df-facts">
                {film.director ? <Link href={`/director/${film.director_slug}`}>{film.director}</Link> : null}
                {film.genres?.length ? <><span className="df-d" />{film.genres.slice(0, 3).join(" · ")}</> : null}
                {runtimeFmt ? <><span className="df-d" />{runtimeFmt}</> : null}
                {cert ? <><span className="df-d" />{cert}</> : null}
                {country ? <><span className="df-d" />{country}</> : null}
              </div>
              {codexBadge}
              {mvChips}
              <div className="df-hactions">
                <MovieListActions filmId={film.id} />
                <EntityActions entityType="film" entityId={film.id} />
                {recs.length ? <Link className="df-like" href={`/movies-like/${film.slug}`}>🎬 Movies like {film.title} →</Link> : null}
              </div>
            </div>
          </div>

          {/* INVITATION — spoiler-free way in; renders right after the headline, before the stat strip */}
          {invitation ? (
            <section className={`df-invite${false && trailer ? " df-invite--vid" : ""}`} id="df-invitation">
              <div className="df-invite__txt">
                <div className="df-invite__head">
                  <h2 className="df-invite__k">An invitation to {film.title}</h2>
                  <span className="df-invite__badge">Spoiler-free</span>
                </div>
                <p className="df-invite__p">{invitation}</p>
                <div className="df-invite__foot">
                  <div className="df-invite__note">The readings below do not hold back.</div>
                  <div className="df-invite__by">— <Link href="/editor">Wonwoo Yoon</Link>, Editor</div>
                </div>
              </div>
              {/* PRESERVED: the trailer now plays in the hero, so this duplicate is disabled.
                  To bring it back, remove the `false && ` here and on the section's df-invite--vid class above. */}
              {false && trailer ? (
                <div className="df-invite__vid">
                  <InviteVideo videoId={trailer.external_id} title={trailer.title ?? `${film.title} trailer`} poster={trailer.thumbnail_url ?? undefined} />
                </div>
              ) : null}
            </section>
          ) : null}

          {/* STAT STRIP — clickable jump links */}
          <div className="df-stats">
            <Link className="df-stat" href="#df-figures"><span className="df-n">{catalogue.length}</span><span className="df-k">Figures</span></Link>
            <Link className="df-stat df-red" href="#df-readings"><span className="df-n">{misreadings.length}</span><span className="df-k">Strong misreadings</span></Link>
            <Link className="df-stat df-teal" href="#df-tropes"><span className="df-n">{tropes.length}</span><span className="df-k">Tropes</span></Link>
            <Link className="df-stat" href="#df-connected"><span className="df-n">{recs.length}</span><span className="df-k">Connected films</span></Link>
          </div>
        </section>

        {/* TOP INFO BAND — ratings + where to watch, directly under the poster/hero.
            AccessCountryProvider keeps the JustWatch band and the verified access layer on one country. */}
        <AccessCountryProvider>
          <FilmTopInfo ratings={ratings} watch={watch} imdbId={film.imdb_id} />

        {/* SECTION TABS — sticky scroll-nav (SEO-safe anchors) */}
        {tabs.length > 1 ? <FilmTabBar tabs={tabs} /> : null}

        {/* WHY WATCH — spoiler-free dossier of what the film offers, across 7 lenses */}
        {whyWatch.length > 0 ? (
          <section className="df-sec" id="df-whywatch">
            <h2 className="df-h2">Why watch {film.title}?</h2>
            <p className="df-sub">A spoiler-free brief on what {film.title} offers — the director&apos;s vision, its craft and ideas, its space and its place in film history. Written for this film by Metatake Editorial (edited by <Link href="/editor">Wonwoo Yoon</Link>), not aggregated from reviews.</p>
            {(() => {
              const ww = questions.find((q) => q.question_type === "why-watch");
              return ww ? (
                <p style={{ margin: "0 0 14px" }}>
                  <Link className="rcp-h" href={`/film/${film.slug}/q/${ww.slug}`}>The case in one read: Why should you watch {film.title}? →</Link>
                </p>
              ) : null;
            })()}
            <div className="ww-grid">
              {whyWatch.map((L, i) => (
                <div key={i} className="ww-lens">
                  <h3 className="ww-h">{WW_TITLE[L.key] ?? L.key.replace(/_/g, " ").toLowerCase()}</h3>
                  <ul className="ww-pts">
                    {(L.points ?? []).map((p, j) => <li key={j}>{p.label ? <b className="ww-lab">{p.label}</b> : null}{p.label ? " — " : ""}{p.text}</li>)}
                  </ul>
                </div>
              ))}
            </div>
          </section>
        ) : null}

        <CinecodexPanel data={codex as Codex | null} title={film.title} subscores={subscores} />

        {/* ATLAS — real-world places (directly under the TakeScore) */}
        {geoCount > 0 ? (
          <section className="df-sec" id="df-atlas">
            <h2 className="df-h2">{film.title} — on the map</h2>
            <p className="cmap-intro">The real places {film.title} is set in and names — geolocated. Click a pin to read what the place means in the film.</p>
            {geoCells >= FILM_LOCATIONS_MIN ? (
              <p style={{ margin: "2px 0 10px", fontSize: 15 }}>
                <Link href={`/film/${film.slug}/locations`}>Where was {film.title} filmed? All {geoMerged} locations, with the scene each one carries →</Link>
              </p>
            ) : null}
            <FilmMap endpoint={`/api/geo?film=${film.slug}`} filmSlug={film.slug} height={460} />
          </section>
        ) : null}

        {/* LINEAGE — where the film sits: awards, canons, auteur line */}
        <FilmLineageSection lineage={lineage} title={film.title} slug={film.slug} listMeta={lnListMeta} movements={movements} />

        {/* RECOMMENDED BY — reverse graph: films whose "Watch next" points here */}
        <FilmRecommendedBy rows={recommendedBy} title={film.title} />

        {/* STRONG MISREADINGS — first; full reading + the leap, grouped by framework family */}
        {misreadings.length > 0 ? (
          <section className="df-sec" id="df-readings">
            <h2 className="df-h2">Strong Misreadings of {film.title}</h2>
            <p className="df-sub">
              {misreadings.length} original critical readings of {film.title}, filed across 14 <Link href="/about#strong-misreadings">frameworks</Link> — each one an argument with a thesis, a deliberate over-reading rather than a summary. Drafted by Metatake Editorial, edited by <Link href="/editor">Wonwoo Yoon</Link>.
            </p>
            {smByFamily.map(({ fam, items }) => (
              <div key={fam.key} className="df-smfam">
                <div className="df-smfam__h">{fam.label}</div>
                {items.map((m, i) => {
                  const F = fw(m.framework);
                  const href = m.figSlug ? `/film/${film.slug}/figure/${m.figSlug}` : null;
                  const fwHref = F.slug && m.framework !== "INVITATION" ? `/strong-misreadings/${F.slug}` : null;
                  return (
                    <div key={i} className="sm-row" style={{ borderLeftColor: F.color }}>
                      <div className="sm-row__top">
                        {fwHref
                          ? <Link className="sm-fw" href={fwHref} style={{ color: F.color }}>{F.label}</Link>
                          : <span className="sm-fw" style={{ color: F.color }}>{F.label}</span>}
                        <span className="sm-via">via {href ? <Link href={href}>{m.figLabel}</Link> : m.figLabel}</span>
                        <SaveChip entityType="take" entityRef={m.id} />
                      </div>
                      {m.take_title ? (
                        <h3 className="sm-row__title">{href ? <Link href={href}>{m.take_title}</Link> : m.take_title}</h3>
                      ) : null}
                      {m.thesis ? <p className="sm-row__thesis sm-row__thesis--full">{m.thesis}</p> : null}
                      {m.leap ? <p className="sm-row__leap"><span className="sm-leap__l">The leap</span> {m.leap}</p> : null}
                    </div>
                  );
                })}
              </div>
            ))}
          </section>
        ) : null}

        {stills.length > 0 ? (
          <div className="df-stills">
            {stills.map((s) => (
              <LightboxImage key={s.id} src={s.thumbnail_url ?? s.url} fullUrl={s.url} alt={s.title ?? `${film.title} still`} className="df-still" caption={`${film.title} — still · TMDB`} />
            ))}
          </div>
        ) : null}

        {/* FIGURES — grouped by kind */}
        {grouped.length > 0 ? (
          <section className="df-sec" id="df-figures">
            <h2 className="df-h2">Figures</h2>
            <p className="df-sub">The characters, objects, places, forms and motifs Metatake singled out in {film.title} — each the anchor for one or more strong misreadings.</p>
            {grouped.map((g) => (
              <div key={g.kind} className="df-fgroup">
                <div className="df-flabel">{KIND_LABEL[g.kind] ?? g.kind}</div>
                {g.items.map((f) => {
                  const n = takeCount[f.id] ?? 0;
                  return (
                    <div key={f.id} className="df-fig">
                      <div className="df-figL">
                        <div className="df-lab">{f.label}</div>
                        <div className="df-figmeta">
                          <span className={`df-rc${n === 0 ? " df-rc--zero" : ""}`}>{n} reading{n === 1 ? "" : "s"}</span>
                          {f.slug ? <Link className="df-figopen" href={`/film/${film.slug}/figure/${f.slug}`}>Open →</Link> : null}
                        </div>
                      </div>
                      <div className="df-figR">
                        {f.description ? <p className="df-figdesc">{f.description}</p> : null}
                      </div>
                    </div>
                  );
                })}
              </div>
            ))}
          </section>
        ) : null}

        {/* CONNECTION MAP */}
        <section className="df-sec" id="df-map">
          <h2 className="df-h2">{film.title} — connection map</h2>
          <p className="cmap-stat"><b>{figures.length}</b> figures · <b>{misreadings.length}</b> strong misreadings · <b>{tropes.length}</b> tropes</p>
          <p className="cmap-intro">Where {film.title} sits in Metatake&rsquo;s critical web of cinema — its figures, the tropes and ideas they carry, its director, and the films nearest by shared reading. Click any node to open it.</p>
          <EntityMap api={`/api/map?type=film&key=${film.slug}`} full={`/map?m=critical&t=film&k=${film.slug}`} />
        </section>

        {/* TROPES */}
        {tropes.length > 0 ? (
          <section className="df-sec" id="df-tropes">
            <h2 className="df-h2">Tropes</h2>
            <p className="df-sub">Cross-film types {film.title} instantiates — shared under <Link href="/tropes">Tropes</Link>. <b>Via</b> = the figure that carries it.</p>
            <div className="df-mlist df-mlist--wide">
              {tropes.map((t) => (
                <div key={t.slug} className={`df-mrow${t.figs.length >= 2 ? " df-top" : ""}`}>
                  <Link className="df-t" href={`/trope/${t.slug}`}>{t.title}</Link>
                  {t.figs.length > 1 ? <span className="df-cnt">{t.figs.length}</span> : null}
                  {t.figs.length ? (
                    <span className="df-via"><span className="df-via__lab">via</span>{t.figs.slice(0, 3).map((fg, i) => (
                      <span key={i}>{i > 0 ? ", " : ""}
                        {fg.slug
                          ? <Link href={`/film/${film.slug}/figure/${fg.slug}`} className="df-f">{fg.label}</Link>
                          : <span className="df-f">{fg.label}</span>}
                      </span>
                    ))}{t.figs.length > 3 ? ` +${t.figs.length - 3}` : ""}</span>
                  ) : null}
                  {t.takeTitle ? (
                    <span className="df-ttl">
                      <span className="df-ttl__lab">reading</span>
                      {t.takeHref
                        ? <Link href={t.takeHref}>{t.takeTitle}<span className="df-ttl__arr"> →</span></Link>
                        : t.takeTitle}
                    </span>
                  ) : null}
                </div>
              ))}
            </div>
          </section>
        ) : null}

        {/* ARCHETYPE — catalog classification of this film's figures */}
        {archGroups.length > 0 ? (
          <section className="df-sec" id="df-archetype">
            <h2 className="df-h2">Archetype</h2>
            <p className="df-sub">What {film.title}&apos;s figures <i>are</i> — their catalog classification, each linking into the <Link href="/catalog">Archetype</Link> catalog. <b>Via</b> = the figure that carries it.</p>
            {archGroups.map((g) => (
              <div key={g.axis} className="df-archgrp">
                <div className="df-flabel">{axisLabel(g.axis)}</div>
                <div className="df-mlist df-mlist--wide">
                  {g.items.map((a) => (
                    <div key={a.slug} className="df-mrow">
                      <Link className="df-t" href={nodeHref(g.axis, a.slug)}>{a.label}</Link>
                      {a.n > 1 ? <span className="df-cnt">{a.n}</span> : null}
                      {a.fig_label ? (
                        <span className="df-via"><span className="df-via__lab">via</span>{" "}
                          {a.fig_slug
                            ? <Link href={`/film/${film.slug}/figure/${a.fig_slug}`} className="df-f">{a.fig_label}</Link>
                            : <span className="df-f">{a.fig_label}</span>}
                        </span>
                      ) : null}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </section>
        ) : null}

        {/* RECEPTION — critics & scholarship (copyright-safe: headlines + ≤10-word verbatim verdicts) */}
        {reception.length > 0 ? (
          <section className="df-sec" id="df-reception">
            <h2 className="df-h2">Reception</h2>
            <p className="df-sub">What critics and scholars have written about {film.title} — each headline links to the source; short quotes are verbatim from publishers&apos; own link previews and paper abstracts.</p>
            {reviews.length > 0 ? (
              <div className="df-rcpgrp">
                <div className="df-flabel">Reviews <span className="df-cnt">{reviews.length}</span></div>
                <div className="rcp-list">
                  {reviews.map((r, i) => (
                    <div key={i} className="rcp-row">
                      <a className="rcp-h" href={r.url} target="_blank" rel="noopener nofollow">{r.headline}</a>
                      <div className="rcp-m">{r.outlet}{r.critic ? ` · ${r.critic}` : ""}{r.year ? ` · ${r.year}` : ""}</div>
                      {r.verdict ? <p className="rcp-v">“{r.verdict}”</p> : null}
                    </div>
                  ))}
                </div>
              </div>
            ) : null}
            {papers.length > 0 ? (
              <div className="df-rcpgrp">
                <div className="df-flabel">Scholarship <span className="df-cnt">{papers.length}</span></div>
                <div className="rcp-list">
                  {papers.map((r, i) => (
                    <div key={i} className="rcp-row">
                      <a className="rcp-h" href={r.url} target="_blank" rel="noopener nofollow">{r.headline}</a>
                      <div className="rcp-m">{r.outlet}{r.critic ? ` · ${r.critic}` : ""}{r.year ? ` · ${r.year}` : ""}</div>
                      {r.verdict ? <p className="rcp-v">“{r.verdict}”</p> : null}
                    </div>
                  ))}
                </div>
              </div>
            ) : null}
            <div className="df-src">Headlines &amp; ≤10-word quotes from publishers&apos; link previews (og:description) and paper abstracts (OpenAlex/Crossref). No article text is stored.</div>
          </section>
        ) : null}

        {/* CURIOUS — the blog's question desk: titles only, reading happens on the Q&A page */}
        {questions.length > 0 ? (
          <section className="df-sec" id="df-curious">
            <h2 className="df-h2">Curious</h2>
            <p className="df-sub">The questions viewers keep asking about {film.title} — answered in full on <Link href="/blog/curious">Curious</Link>, the Metatake blog&apos;s question desk. Spoiler-heavy titles are masked.</p>
            <div className="rcp-list">
              {questions.map((q) => (
                <div key={q.slug} className="rcp-row">
                  <Link className="rcp-h" href={`/film/${film.slug}/q/${q.slug}`}>
                    {(q.title_spoiler && q.display_title) ? q.display_title : q.title}
                  </Link>
                  <div className="rcp-m">
                    {q.question_type ? q.question_type : "question"}
                    {q.spoiler_level === "major" ? " · discusses the ending" : ""}
                  </div>
                </div>
              ))}
            </div>
          </section>
        ) : null}

        {/* WATCH NEXT — curated 9 next films (LLM, with the bridge), linked if in our DB */}
        {watchNext.length > 0 ? (
          <section className="df-sec" id="df-watchnext">
            <h2 className="df-h2">Watch next</h2>
            <p className="df-sub">Where to go after {film.title} — nine films that continue its conversation, each chosen for a specific bridge. Curated, not algorithmic.</p>
            <div className="wn-list">
              {watchNext.map((w, i) => {
                const href = w.target_slug ? `/film/${w.target_slug}` : null;
                const poster = w.target_poster ?? w.poster_path;
                const title = w.target_title ?? w.rec_title;
                const year = w.target_year ?? w.rec_year;
                return (
                  <div key={i} className="wn-card">
                    <div className="wn-pos">{i + 1}</div>
                    {poster ? (
                      href
                        ? <Link href={href} className="wn-pl">{/* eslint-disable-next-line @next/next/no-img-element */}<img className="wn-pi" src={`${IMG}/w185${poster}`} alt="" loading="lazy" />{w.target_slug ? <PosterActions slug={w.target_slug} compact /> : null}</Link>
                        // eslint-disable-next-line @next/next/no-img-element
                        : <img className="wn-pi" src={`${IMG}/w185${poster}`} alt="" loading="lazy" />
                    ) : <div className="wn-pi wn-pi--empty" aria-hidden="true" />}
                    <div className="wn-tx">
                      <div className="wn-h">{href ? <Link href={href}>{title}</Link> : title} <span className="wn-yr">({year ?? "?"})</span></div>
                      {w.rec_director ? <div className="wn-dir">{w.rec_director}</div> : null}
                      {w.reason ? <p className="wn-why">{w.reason}</p> : null}
                      {!href && w.tmdb_id ? (
                        <span className="wn-ext">not yet on Metatake · <a href={`https://www.themoviedb.org/movie/${w.tmdb_id}`} target="_blank" rel="noopener nofollow">TMDB ↗</a></span>
                      ) : null}
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        ) : null}

        {/* CONNECTED FILMS — top-5 kin with evidence; full ranked list lives on /movies-like */}
        {recs.length > 0 ? (
          <section className="df-sec" id="df-connected">
            <h2 className="df-h2">The 5 films most connected to {film.title}<Link className="df-more" href={`/movies-like/${film.slug}`}>full ranking →</Link></h2>
            <p className="df-sub">Nearest neighbours in meaning-space, ranked by shared tropes and taste-vector proximity. <Link href="/methodology#connections">How connections are computed →</Link></p>
            <div className="df-conn">
              {recs.map((r, i) => (
                <div key={r.slug} className="df-crow" style={{ display: "flex", gap: 12, alignItems: "center", padding: "7px 0" }}>
                  <span style={{ flex: "0 0 26px", textAlign: "right", fontWeight: 800, fontSize: 15, opacity: i === 0 ? .95 : .45, fontVariantNumeric: "tabular-nums" }}><span style={{ fontSize: "0.65em", opacity: .7 }}>#</span>{i + 1}</span>
                  {r.poster_path ? (
                    <Link href={`/film/${r.slug}`} aria-label={r.title} style={{ flex: "0 0 40px" }}>
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={`${IMG}/w92${r.poster_path}`} alt="" width={40} height={60} loading="lazy" style={{ width: 40, height: 60, objectFit: "cover", borderRadius: 5, display: "block" }} />
                    </Link>
                  ) : <span style={{ flex: "0 0 40px", height: 60, borderRadius: 5, background: "rgba(0,0,0,.06)" }} aria-hidden="true" />}
                  <span style={{ minWidth: 0 }}>
                    <Link className="df-ti" href={`/film/${r.slug}`}>{r.title}</Link>{" "}
                    <span className="df-cyr">({r.year ?? "?"})</span>
                    <span style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 4 }}>
                      {r.cos != null ? (
                        <span style={{ fontSize: 11, fontWeight: 700, padding: "1px 7px", borderRadius: 999, background: "rgba(31,111,178,.10)", color: "#1a4e7a" }}>taste match {Math.round(r.cos * 100)}%</span>
                      ) : null}
                      <span style={{ fontSize: 11, fontWeight: 700, padding: "1px 7px", borderRadius: 999, background: "rgba(15,110,86,.10)", color: "#0b5343" }}>
                        {r.sharedN > 0 ? `${r.sharedN} shared trope${r.sharedN > 1 ? "s" : ""}` : "taste neighbour"}
                      </span>
                    </span>
                  </span>
                </div>
              ))}
            </div>
            <p style={{ fontSize: 11.5, opacity: .6, margin: "12px 0 0" }}>
              Computed by Metatake&apos;s connection engine · Edited by <Link href="/editor">Wonwoo Yoon</Link>
              {recsUpdated ? <> · Updated {new Date(recsUpdated).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })}</> : null}
            </p>
          </section>
        ) : null}

        {/* COUNTERPOINTS — same trope, most distant readings. Every sentence is derived
            from entity_edges + takes at render time, so it changes when the data does. */}
        {counterpoints.length > 0 ? (
          <section className="df-sec" id="df-counterpoints">
            <h2 className="df-h2">Counterpoints — same shape, opposite meaning</h2>
            <p className="df-sub">
              Films that stage one of <b>{film.title}</b>&apos;s own tropes but read it against the grain.
              Kinship maps can find lookalikes; only a reading-level graph can find arguments.
            </p>
            <div className="df-conn">
              {counterpoints.map((c) => (
                <div key={`${c.film.slug}-${c.trope.slug}`} className="df-crow">
                  <Link className="df-ti" href={`/film/${c.film.slug}`}>{c.film.title}</Link>{" "}
                  <span className="df-cyr">({c.film.year ?? "?"}{c.film.director ? `, ${c.film.director}` : ""})</span>{" "}
                  <span style={{ fontSize: 11, fontWeight: 700, padding: "1px 7px", borderRadius: 999, background: "rgba(230,126,34,.12)", color: "#9a4d0c", whiteSpace: "nowrap" }}>
                    readings diverge {Math.round((1 - c.sim) * 100)}%
                  </span>
                  <p className="wn-why">
                    Both stage <Link href={`/trope/${c.trope.slug}`}>{c.trope.title}</Link>
                    {c.here?.take && c.there?.take ? (
                      <>
                        {" "}— here it becomes{" "}
                        {c.here.figure
                          ? <Link href={`/film/${film.slug}/figure/${c.here.figure}`}>&ldquo;{c.here.take}&rdquo;</Link>
                          : <>&ldquo;{c.here.take}&rdquo;</>}
                        , there{" "}
                        {c.there.figure
                          ? <Link href={`/film/${c.film.slug}/figure/${c.there.figure}`}>&ldquo;{c.there.take}&rdquo;</Link>
                          : <>&ldquo;{c.there.take}&rdquo;</>}
                        .
                      </>
                    ) : "."}
                  </p>
                </div>
              ))}
            </div>
            <p style={{ fontSize: 11.5, opacity: .6, margin: "12px 0 0" }}>
              <b>readings diverge N%</b> = distance between the two films&apos; reading vectors on the shared trope
              (100% = opposite readings). Computed by Metatake&apos;s connection engine · Edited by <Link href="/editor">Wonwoo Yoon</Link> · <Link href="/methodology#connections">How it works →</Link>
            </p>
          </section>
        ) : null}

        {/* CREDITS — key crafts, crawlable, linking to /credits/[person] read pages */}
        {crew.length > 0 ? (
          <section className="df-sec" id="df-crew">
            <h2 className="df-h2">Credits — who made {film.title}</h2>
            <p className="df-sub">The key crafts behind the film. Each name opens their body of work: the directors they keep returning to, and where their films are read on Metatake.</p>
            <div className="rcp-list">
              {film.director ? (
                <div className="rcp-row">
                  <span className="rcp-m" style={{ minWidth: 150 }}>Director</span>
                  {film.director_slug ? <Link className="rcp-h" href={`/director/${film.director_slug}`}>{film.director}</Link> : <span className="rcp-h">{film.director}</span>}
                </div>
              ) : null}
              {crew.map((c) => (
                <div key={c.craft} className="rcp-row">
                  <span className="rcp-m" style={{ minWidth: 150 }}>{CRAFTS[c.craft].label}</span>
                  <span>
                    {c.people.map((pp, i) => (
                      <span key={pp.id}>
                        {i > 0 ? ", " : ""}
                        <Link className="rcp-h" href={`/credits/${personSlug(pp.name, pp.id)}`}>{pp.name}</Link>
                      </span>
                    ))}
                  </span>
                </div>
              ))}
            </div>
            {film.tmdb_id ? (
              <div className="df-src"><Link href={`/credits?f=${film.tmdb_id}`}>Open in the interactive Credits explorer →</Link> · Credits data from TMDB</div>
            ) : null}
          </section>
        ) : null}

        {/* FILM INFO — accordion */}
        {(film.overview || cast.length || extra.writers?.length || film.release_date || extra.country?.length || trailer) ? (
          <details className="df-finfo" id="df-information">
            <summary>Film info &amp; credits</summary>
            <div className="df-finfo__body">
              {film.overview ? <p className="df-ov">{film.overview}</p> : null}
              {trailer && !invitation ? (
                <div className="df-trailer">
                  <YouTubeFacade videoId={trailer.external_id} title={trailer.title ?? "Trailer"} thumbnailUrl={trailer.thumbnail_url ?? undefined} attribution={trailer.attribution ?? undefined} />
                </div>
              ) : null}
              <dl className="df-dl">
                {film.director ? <><dt>Director</dt><dd><Link href={`/director/${film.director_slug}`}>{film.director}</Link></dd></> : null}
                {cast.length ? <><dt>Cast</dt><dd>{cast.slice(0, 5).map((c) => c.character ? `${c.name} (${c.character})` : c.name).join(", ")}</dd></> : null}
                {extra.writers?.length ? <><dt>Writing</dt><dd>{extra.writers.join(", ")}</dd></> : null}
                {film.release_date ? <><dt>Released</dt><dd>{film.release_date}</dd></> : null}
                {runtimeFmt ? <><dt>Runtime</dt><dd>{runtimeFmt}</dd></> : null}
                {film.genres?.length ? <><dt>Genre</dt><dd>{film.genres.join(", ")}</dd></> : null}
                {cert ? <><dt>Rated</dt><dd>{cert}</dd></> : null}
                {extra.original_language ? <><dt>Language</dt><dd>{extra.original_language.toUpperCase()}</dd></> : null}
                {extra.country?.length ? <><dt>Country</dt><dd>{extra.country.join(", ")}</dd></> : null}
                {extra.collection ? <><dt>Collection</dt><dd>{extra.collection}</dd></> : null}
              </dl>
              <div className="df-src">Data &amp; images via TMDB. Not endorsed or certified by TMDB.</div>
            </div>
          </details>
        ) : null}

        {/* WHERE TO WATCH — verified access layer, moved to the final tab */}
        <section className="df-sec" id="df-watch">
          <AccessSummary watch={watch} record={accessRec} slug={film.slug} title={film.title} />
          {accessRec ? <AccessEnrichment record={accessRec} tmdbId={film.tmdb_id} /> : null}
        </section>
        </AccessCountryProvider>

        <div className="df-seq">
          <SeqNav kind="film" id={film.id} />
        </div>

        <Provenance created={film.created_at} />
      </div>
    </div>
  );
}
