// lib/discoveries/digests.ts
// Metatake Discoveries — the newborn-film-site radar at /discoveries.
// Append-only: prepend new digests at the TOP (newest first).
//
// Canonical spec: HANDOFF-발견피드.md (repo root).
//
// TWO TIERS (owner call 2026-07-18):
//  - observed[]  : the observation log. AUTO — generated by discovery/build_digest.py
//                  from the weekly scan (Haiku legit-category gate). Rendered nofollow.
//                  It is a record that we saw the site, NOT an endorsement.
//  - featured[]  : editor's picks. Owner promotes an entry here and writes a real
//                  1–2 sentence note by hand. Rendered dofollow — a genuine gift.
//
// Regenerate a draft: cd discovery && python3 build_digest.py --id … --label … --scanned …
// then paste the block, write the intro, and (optionally) promote a few to featured.

export type DiscoveryCategory =
  | "criticism" | "journal" | "news" | "festival" | "venue"
  | "archive" | "podcast" | "education" | "database" | "curation";

export const CATEGORY_LABEL: Record<DiscoveryCategory, string> = {
  criticism: "Criticism",
  journal: "Journal",
  news: "Film news",
  festival: "Festival",
  venue: "Cinema / venue",
  archive: "Archive",
  podcast: "Podcast",
  education: "Education",
  database: "Database",
  curation: "Curation",
};

export type Observed = {
  domain: string;
  category: DiscoveryCategory;
  /** ISO-ish language tag from the page, or "?" */
  lang: string;
};

export type Featured = {
  domain: string;
  /** the site's own name */
  title: string;
  /** owner's editorial note, 1–2 sentences */
  note: string;
  category: DiscoveryCategory;
  lang: string;
};

export type Digest = {
  /** permanent anchor "YYYY-MM-DD-slug". NEVER change after publish. */
  id: string;
  /** publish date, KST, YYYY-MM-DD */
  date: string;
  /** human range label, e.g. "Week of Jul 10–16, 2026" */
  rangeLabel: string;
  /** newly registered domains read that period (context number) */
  scanned: number;
  /** factual prose lead — one paragraph. No links (links live in the lists). */
  intro: string;
  featured: Featured[];
  observed: Observed[];
};

export const DIGESTS: Digest[] = [
  {
    id: "2026-07-18-wk29",
    date: "2026-07-18",
    rangeLabel: "Week of Jul 10–16, 2026",
    scanned: 490000,
    intro:
      "In the week of July 10–16, 2026, the discovery scanner read about 490,000 newly registered domains and, after filtering and a first-pass read, surfaced 23 that look like genuine new film-culture sites — festivals, cinemas, review blogs, and film databases rather than piracy mirrors or parked names. Among them a Kurdish film festival in Denmark and a Jewish film-days program in Hamburg, a Gujarati-language review site, Korea's moviepress.kr film-news outlet, a French rating-and-curation site, and two community-built film databases. The list below is an observation record, not an endorsement — links are nofollow, and any site can ask to be removed.",
    featured: [
      // Owner promotes here and writes a real 1–2 sentence note. dofollow.
    ],
    observed: [
      { domain: "kurdiskfilmfestival.dk", category: "festival", lang: "da" },
      { domain: "juedischefilmtage.hamburg", category: "festival", lang: "de" },
      { domain: "cinematepito.com", category: "venue", lang: "es" },
      { domain: "docafilmfestival.com", category: "festival", lang: "en" },
      { domain: "newfilmmakersny.com", category: "festival", lang: "en" },
      { domain: "gujaratifilmreview.in", category: "criticism", lang: "gu" },
      { domain: "odeonkino.pro", category: "venue", lang: "no" },
      { domain: "themoviemen.nl", category: "podcast", lang: "nl" },
      { domain: "sundaymovies.club", category: "curation", lang: "tr" },
      { domain: "infernomovies.blog", category: "criticism", lang: "de" },
      { domain: "ericscinema.club", category: "venue", lang: "en" },
      { domain: "thatfilmydude.net", category: "criticism", lang: "en" },
      { domain: "runtimemovieclub.com", category: "venue", lang: "en" },
      { domain: "cineavis.fr", category: "criticism", lang: "fr" },
      { domain: "kino-nevelsk.ru", category: "venue", lang: "ru" },
      { domain: "moviepress.kr", category: "news", lang: "ko" },
      { domain: "usafilmnews.com", category: "news", lang: "en" },
      { domain: "streamingmovienightmovieguide.com", category: "news", lang: "en" },
      { domain: "plazmakino.ru", category: "venue", lang: "ru" },
      { domain: "nettetalerkinoopenair.com", category: "venue", lang: "de" },
      { domain: "cinemaidirector.com", category: "education", lang: "pt-br" },
      { domain: "cineqissa.net", category: "database", lang: "en" },
      { domain: "thefilmspreadsheet.com", category: "database", lang: "en" },
    ],
  },
];
